// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: sesame/v1alpha1/tunnel.proto

package tun

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*TunnelRequest_Connect_
	Data isTunnelRequest_Data `protobuf_oneof:"data"`
}

func (x *TunnelRequest) Reset() {
	*x = TunnelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sesame_v1alpha1_tunnel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelRequest) ProtoMessage() {}

func (x *TunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_tunnel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelRequest.ProtoReflect.Descriptor instead.
func (*TunnelRequest) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_tunnel_proto_rawDescGZIP(), []int{0}
}

func (m *TunnelRequest) GetData() isTunnelRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *TunnelRequest) GetConnect() *TunnelRequest_Connect {
	if x, ok := x.GetData().(*TunnelRequest_Connect_); ok {
		return x.Connect
	}
	return nil
}

type isTunnelRequest_Data interface {
	isTunnelRequest_Data()
}

type TunnelRequest_Connect_ struct {
	Connect *TunnelRequest_Connect `protobuf:"bytes,1,opt,name=connect,proto3,oneof"` // ping
}

func (*TunnelRequest_Connect_) isTunnelRequest_Data() {}

type TunnelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*TunnelResponse_Connect_
	Data isTunnelResponse_Data `protobuf_oneof:"data"`
}

func (x *TunnelResponse) Reset() {
	*x = TunnelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sesame_v1alpha1_tunnel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelResponse) ProtoMessage() {}

func (x *TunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_tunnel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelResponse.ProtoReflect.Descriptor instead.
func (*TunnelResponse) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_tunnel_proto_rawDescGZIP(), []int{1}
}

func (m *TunnelResponse) GetData() isTunnelResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *TunnelResponse) GetConnect() *TunnelResponse_Connect {
	if x, ok := x.GetData().(*TunnelResponse_Connect_); ok {
		return x.Connect
	}
	return nil
}

type isTunnelResponse_Data interface {
	isTunnelResponse_Data()
}

type TunnelResponse_Connect_ struct {
	Connect *TunnelResponse_Connect `protobuf:"bytes,1,opt,name=connect,proto3,oneof"` // pong
}

func (*TunnelResponse_Connect_) isTunnelResponse_Data() {}

type TunnelRequest_Connect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TunnelRequest_Connect) Reset() {
	*x = TunnelRequest_Connect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sesame_v1alpha1_tunnel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelRequest_Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelRequest_Connect) ProtoMessage() {}

func (x *TunnelRequest_Connect) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_tunnel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelRequest_Connect.ProtoReflect.Descriptor instead.
func (*TunnelRequest_Connect) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_tunnel_proto_rawDescGZIP(), []int{0, 0}
}

type TunnelResponse_Connect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TunnelResponse_Connect) Reset() {
	*x = TunnelResponse_Connect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sesame_v1alpha1_tunnel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelResponse_Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelResponse_Connect) ProtoMessage() {}

func (x *TunnelResponse_Connect) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_tunnel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelResponse_Connect.ProtoReflect.Descriptor instead.
func (*TunnelResponse_Connect) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_tunnel_proto_rawDescGZIP(), []int{1, 0}
}

var File_sesame_v1alpha1_tunnel_proto protoreflect.FileDescriptor

var file_sesame_v1alpha1_tunnel_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x65, 0x73, 0x61, 0x6d, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2f, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x73, 0x65, 0x73, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x22,
	0x66, 0x0a, 0x0d, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x42, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x73, 0x65, 0x73, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x1a, 0x09, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x42,
	0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x68, 0x0a, 0x0e, 0x54, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x73, 0x65, 0x73,
	0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x54, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x1a, 0x09,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x32, 0x60, 0x0a, 0x0d, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4f, 0x0a, 0x06, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1e, 0x2e, 0x73,
	0x65, 0x73, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x54,
	0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73,
	0x65, 0x73, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x54,
	0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6a, 0x6f, 0x65, 0x79, 0x63, 0x75, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x2f, 0x73, 0x65,
	0x73, 0x61, 0x6d, 0x65, 0x2f, 0x74, 0x75, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sesame_v1alpha1_tunnel_proto_rawDescOnce sync.Once
	file_sesame_v1alpha1_tunnel_proto_rawDescData = file_sesame_v1alpha1_tunnel_proto_rawDesc
)

func file_sesame_v1alpha1_tunnel_proto_rawDescGZIP() []byte {
	file_sesame_v1alpha1_tunnel_proto_rawDescOnce.Do(func() {
		file_sesame_v1alpha1_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(file_sesame_v1alpha1_tunnel_proto_rawDescData)
	})
	return file_sesame_v1alpha1_tunnel_proto_rawDescData
}

var file_sesame_v1alpha1_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sesame_v1alpha1_tunnel_proto_goTypes = []interface{}{
	(*TunnelRequest)(nil),          // 0: sesame.v1alpha1.TunnelRequest
	(*TunnelResponse)(nil),         // 1: sesame.v1alpha1.TunnelResponse
	(*TunnelRequest_Connect)(nil),  // 2: sesame.v1alpha1.TunnelRequest.Connect
	(*TunnelResponse_Connect)(nil), // 3: sesame.v1alpha1.TunnelResponse.Connect
}
var file_sesame_v1alpha1_tunnel_proto_depIdxs = []int32{
	2, // 0: sesame.v1alpha1.TunnelRequest.connect:type_name -> sesame.v1alpha1.TunnelRequest.Connect
	3, // 1: sesame.v1alpha1.TunnelResponse.connect:type_name -> sesame.v1alpha1.TunnelResponse.Connect
	0, // 2: sesame.v1alpha1.TunnelService.Tunnel:input_type -> sesame.v1alpha1.TunnelRequest
	1, // 3: sesame.v1alpha1.TunnelService.Tunnel:output_type -> sesame.v1alpha1.TunnelResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sesame_v1alpha1_tunnel_proto_init() }
func file_sesame_v1alpha1_tunnel_proto_init() {
	if File_sesame_v1alpha1_tunnel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sesame_v1alpha1_tunnel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sesame_v1alpha1_tunnel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sesame_v1alpha1_tunnel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelRequest_Connect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sesame_v1alpha1_tunnel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelResponse_Connect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sesame_v1alpha1_tunnel_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*TunnelRequest_Connect_)(nil),
	}
	file_sesame_v1alpha1_tunnel_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*TunnelResponse_Connect_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sesame_v1alpha1_tunnel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sesame_v1alpha1_tunnel_proto_goTypes,
		DependencyIndexes: file_sesame_v1alpha1_tunnel_proto_depIdxs,
		MessageInfos:      file_sesame_v1alpha1_tunnel_proto_msgTypes,
	}.Build()
	File_sesame_v1alpha1_tunnel_proto = out.File
	file_sesame_v1alpha1_tunnel_proto_rawDesc = nil
	file_sesame_v1alpha1_tunnel_proto_goTypes = nil
	file_sesame_v1alpha1_tunnel_proto_depIdxs = nil
}
