// Code generated by protoc-gen-go-copy. DO NOT EDIT.
// source: sesame/type/tls.proto

package tls

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *TLSOptions) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *TLSOptions:
		x.ServerName = v.GetServerName()
		x.AlpnProtocols = v.GetAlpnProtocols()
		x.MinVersion = v.GetMinVersion()
		x.MaxVersion = v.GetMaxVersion()
		x.FingerprintPreset = v.GetFingerprintPreset()
		x.CipherSuites = v.GetCipherSuites()
		x.InsecureSkipVerify = v.GetInsecureSkipVerify()
		x.CaCertificates = v.GetCaCertificates()
		x.ClientCertificate = v.GetClientCertificate()
		x.ClientPrivateKey = v.GetClientPrivateKey()
		x.SessionTicket = v.GetSessionTicket()
	default:
		if v, ok := v.(interface{ GetServerName() string }); ok {
			x.ServerName = v.GetServerName()
		}
		if v, ok := v.(interface{ GetAlpnProtocols() []string }); ok {
			x.AlpnProtocols = v.GetAlpnProtocols()
		}
		if v, ok := v.(interface{ GetMinVersion() TLSVersion }); ok {
			x.MinVersion = v.GetMinVersion()
		}
		if v, ok := v.(interface{ GetMaxVersion() TLSVersion }); ok {
			x.MaxVersion = v.GetMaxVersion()
		}
		if v, ok := v.(interface{ GetFingerprintPreset() FingerprintPreset }); ok {
			x.FingerprintPreset = v.GetFingerprintPreset()
		}
		if v, ok := v.(interface{ GetCipherSuites() []uint32 }); ok {
			x.CipherSuites = v.GetCipherSuites()
		}
		if v, ok := v.(interface{ GetInsecureSkipVerify() bool }); ok {
			x.InsecureSkipVerify = v.GetInsecureSkipVerify()
		}
		if v, ok := v.(interface{ GetCaCertificates() []byte }); ok {
			x.CaCertificates = v.GetCaCertificates()
		}
		if v, ok := v.(interface{ GetClientCertificate() []byte }); ok {
			x.ClientCertificate = v.GetClientCertificate()
		}
		if v, ok := v.(interface{ GetClientPrivateKey() []byte }); ok {
			x.ClientPrivateKey = v.GetClientPrivateKey()
		}
		if v, ok := v.(interface{ GetSessionTicket() []byte }); ok {
			x.SessionTicket = v.GetSessionTicket()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *TLSOptions) Proto_ShallowClone() (c *TLSOptions) {
	if x != nil {
		c = new(TLSOptions)
		c.ServerName = x.ServerName
		c.AlpnProtocols = x.AlpnProtocols
		c.MinVersion = x.MinVersion
		c.MaxVersion = x.MaxVersion
		c.FingerprintPreset = x.FingerprintPreset
		c.CipherSuites = x.CipherSuites
		c.InsecureSkipVerify = x.InsecureSkipVerify
		c.CaCertificates = x.CaCertificates
		c.ClientCertificate = x.ClientCertificate
		c.ClientPrivateKey = x.ClientPrivateKey
		c.SessionTicket = x.SessionTicket
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *TLSHandshakeResult) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *TLSHandshakeResult:
		x.NegotiatedProtocol = v.GetNegotiatedProtocol()
		x.CipherSuite = v.GetCipherSuite()
		x.TlsVersion = v.GetTlsVersion()
		x.ServerName = v.GetServerName()
		x.PeerCertificates = v.GetPeerCertificates()
		x.ResumptionTicket = v.GetResumptionTicket()
		x.AppliedPreset = v.GetAppliedPreset()
	default:
		if v, ok := v.(interface{ GetNegotiatedProtocol() string }); ok {
			x.NegotiatedProtocol = v.GetNegotiatedProtocol()
		}
		if v, ok := v.(interface{ GetCipherSuite() uint32 }); ok {
			x.CipherSuite = v.GetCipherSuite()
		}
		if v, ok := v.(interface{ GetTlsVersion() TLSVersion }); ok {
			x.TlsVersion = v.GetTlsVersion()
		}
		if v, ok := v.(interface{ GetServerName() string }); ok {
			x.ServerName = v.GetServerName()
		}
		if v, ok := v.(interface{ GetPeerCertificates() [][]byte }); ok {
			x.PeerCertificates = v.GetPeerCertificates()
		}
		if v, ok := v.(interface{ GetResumptionTicket() []byte }); ok {
			x.ResumptionTicket = v.GetResumptionTicket()
		}
		if v, ok := v.(interface{ GetAppliedPreset() FingerprintPreset }); ok {
			x.AppliedPreset = v.GetAppliedPreset()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *TLSHandshakeResult) Proto_ShallowClone() (c *TLSHandshakeResult) {
	if x != nil {
		c = new(TLSHandshakeResult)
		c.NegotiatedProtocol = x.NegotiatedProtocol
		c.CipherSuite = x.CipherSuite
		c.TlsVersion = x.TlsVersion
		c.ServerName = x.ServerName
		c.PeerCertificates = x.PeerCertificates
		c.ResumptionTicket = x.ResumptionTicket
		c.AppliedPreset = x.AppliedPreset
	}
	return
}
