// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: sesame/v1alpha1/remotecontrol.proto

package rc

import (
	netaddr "github.com/joeycumines/sesame/type/netaddr"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NetConnRequest models a message sent from a RemoteControl.NetConn client to the server.
// See also documentation of that method.
type NetConnRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*NetConnRequest_Dial_
	//	*NetConnRequest_Bytes
	Data          isNetConnRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetConnRequest) Reset() {
	*x = NetConnRequest{}
	mi := &file_sesame_v1alpha1_remotecontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetConnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetConnRequest) ProtoMessage() {}

func (x *NetConnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_remotecontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetConnRequest.ProtoReflect.Descriptor instead.
func (*NetConnRequest) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_remotecontrol_proto_rawDescGZIP(), []int{0}
}

func (x *NetConnRequest) GetData() isNetConnRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *NetConnRequest) GetDial() *NetConnRequest_Dial {
	if x != nil {
		if x, ok := x.Data.(*NetConnRequest_Dial_); ok {
			return x.Dial
		}
	}
	return nil
}

func (x *NetConnRequest) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Data.(*NetConnRequest_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

type isNetConnRequest_Data interface {
	isNetConnRequest_Data()
}

type NetConnRequest_Dial_ struct {
	Dial *NetConnRequest_Dial `protobuf:"bytes,1,opt,name=dial,proto3,oneof"`
}

type NetConnRequest_Bytes struct {
	Bytes []byte `protobuf:"bytes,2,opt,name=bytes,proto3,oneof"`
}

func (*NetConnRequest_Dial_) isNetConnRequest_Data() {}

func (*NetConnRequest_Bytes) isNetConnRequest_Data() {}

// NetConnResponse models a message sent from a RemoteControl.NetConn server to the client.
// See also documentation of that method.
type NetConnResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*NetConnResponse_Conn_
	//	*NetConnResponse_Bytes
	Data          isNetConnResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetConnResponse) Reset() {
	*x = NetConnResponse{}
	mi := &file_sesame_v1alpha1_remotecontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetConnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetConnResponse) ProtoMessage() {}

func (x *NetConnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_remotecontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetConnResponse.ProtoReflect.Descriptor instead.
func (*NetConnResponse) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_remotecontrol_proto_rawDescGZIP(), []int{1}
}

func (x *NetConnResponse) GetData() isNetConnResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *NetConnResponse) GetConn() *NetConnResponse_Conn {
	if x != nil {
		if x, ok := x.Data.(*NetConnResponse_Conn_); ok {
			return x.Conn
		}
	}
	return nil
}

func (x *NetConnResponse) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Data.(*NetConnResponse_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

type isNetConnResponse_Data interface {
	isNetConnResponse_Data()
}

type NetConnResponse_Conn_ struct {
	Conn *NetConnResponse_Conn `protobuf:"bytes,1,opt,name=conn,proto3,oneof"`
}

type NetConnResponse_Bytes struct {
	Bytes []byte `protobuf:"bytes,2,opt,name=bytes,proto3,oneof"`
}

func (*NetConnResponse_Conn_) isNetConnResponse_Data() {}

func (*NetConnResponse_Bytes) isNetConnResponse_Data() {}

// Dial models the initial request.
type NetConnRequest_Dial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *netaddr.NetAddr       `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetConnRequest_Dial) Reset() {
	*x = NetConnRequest_Dial{}
	mi := &file_sesame_v1alpha1_remotecontrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetConnRequest_Dial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetConnRequest_Dial) ProtoMessage() {}

func (x *NetConnRequest_Dial) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_remotecontrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetConnRequest_Dial.ProtoReflect.Descriptor instead.
func (*NetConnRequest_Dial) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_remotecontrol_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NetConnRequest_Dial) GetAddress() *netaddr.NetAddr {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *NetConnRequest_Dial) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// Conn models the initial response.
type NetConnResponse_Conn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Local         *netaddr.NetAddr       `protobuf:"bytes,1,opt,name=local,proto3" json:"local,omitempty"`
	Remote        *netaddr.NetAddr       `protobuf:"bytes,2,opt,name=remote,proto3" json:"remote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetConnResponse_Conn) Reset() {
	*x = NetConnResponse_Conn{}
	mi := &file_sesame_v1alpha1_remotecontrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetConnResponse_Conn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetConnResponse_Conn) ProtoMessage() {}

func (x *NetConnResponse_Conn) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_remotecontrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetConnResponse_Conn.ProtoReflect.Descriptor instead.
func (*NetConnResponse_Conn) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_remotecontrol_proto_rawDescGZIP(), []int{1, 0}
}

func (x *NetConnResponse_Conn) GetLocal() *netaddr.NetAddr {
	if x != nil {
		return x.Local
	}
	return nil
}

func (x *NetConnResponse_Conn) GetRemote() *netaddr.NetAddr {
	if x != nil {
		return x.Remote
	}
	return nil
}

var File_sesame_v1alpha1_remotecontrol_proto protoreflect.FileDescriptor

const file_sesame_v1alpha1_remotecontrol_proto_rawDesc = "" +
	"\n" +
	"#sesame/v1alpha1/remotecontrol.proto\x12\x0fsesame.v1alpha1\x1a\x1egoogle/protobuf/duration.proto\x1a\x19sesame/type/netaddr.proto\"\xd9\x01\n" +
	"\x0eNetConnRequest\x12:\n" +
	"\x04dial\x18\x01 \x01(\v2$.sesame.v1alpha1.NetConnRequest.DialH\x00R\x04dial\x12\x16\n" +
	"\x05bytes\x18\x02 \x01(\fH\x00R\x05bytes\x1ak\n" +
	"\x04Dial\x12.\n" +
	"\aaddress\x18\x01 \x01(\v2\x14.sesame.type.NetAddrR\aaddress\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeoutB\x06\n" +
	"\x04data\"\xd0\x01\n" +
	"\x0fNetConnResponse\x12;\n" +
	"\x04conn\x18\x01 \x01(\v2%.sesame.v1alpha1.NetConnResponse.ConnH\x00R\x04conn\x12\x16\n" +
	"\x05bytes\x18\x02 \x01(\fH\x00R\x05bytes\x1a`\n" +
	"\x04Conn\x12*\n" +
	"\x05local\x18\x01 \x01(\v2\x14.sesame.type.NetAddrR\x05local\x12,\n" +
	"\x06remote\x18\x02 \x01(\v2\x14.sesame.type.NetAddrR\x06remoteB\x06\n" +
	"\x04data2c\n" +
	"\rRemoteControl\x12R\n" +
	"\aNetConn\x12\x1f.sesame.v1alpha1.NetConnRequest\x1a .sesame.v1alpha1.NetConnResponse\"\x00(\x010\x01B\"Z github.com/joeycumines/sesame/rcb\x06proto3"

var (
	file_sesame_v1alpha1_remotecontrol_proto_rawDescOnce sync.Once
	file_sesame_v1alpha1_remotecontrol_proto_rawDescData []byte
)

func file_sesame_v1alpha1_remotecontrol_proto_rawDescGZIP() []byte {
	file_sesame_v1alpha1_remotecontrol_proto_rawDescOnce.Do(func() {
		file_sesame_v1alpha1_remotecontrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sesame_v1alpha1_remotecontrol_proto_rawDesc), len(file_sesame_v1alpha1_remotecontrol_proto_rawDesc)))
	})
	return file_sesame_v1alpha1_remotecontrol_proto_rawDescData
}

var file_sesame_v1alpha1_remotecontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sesame_v1alpha1_remotecontrol_proto_goTypes = []any{
	(*NetConnRequest)(nil),       // 0: sesame.v1alpha1.NetConnRequest
	(*NetConnResponse)(nil),      // 1: sesame.v1alpha1.NetConnResponse
	(*NetConnRequest_Dial)(nil),  // 2: sesame.v1alpha1.NetConnRequest.Dial
	(*NetConnResponse_Conn)(nil), // 3: sesame.v1alpha1.NetConnResponse.Conn
	(*netaddr.NetAddr)(nil),      // 4: sesame.type.NetAddr
	(*durationpb.Duration)(nil),  // 5: google.protobuf.Duration
}
var file_sesame_v1alpha1_remotecontrol_proto_depIdxs = []int32{
	2, // 0: sesame.v1alpha1.NetConnRequest.dial:type_name -> sesame.v1alpha1.NetConnRequest.Dial
	3, // 1: sesame.v1alpha1.NetConnResponse.conn:type_name -> sesame.v1alpha1.NetConnResponse.Conn
	4, // 2: sesame.v1alpha1.NetConnRequest.Dial.address:type_name -> sesame.type.NetAddr
	5, // 3: sesame.v1alpha1.NetConnRequest.Dial.timeout:type_name -> google.protobuf.Duration
	4, // 4: sesame.v1alpha1.NetConnResponse.Conn.local:type_name -> sesame.type.NetAddr
	4, // 5: sesame.v1alpha1.NetConnResponse.Conn.remote:type_name -> sesame.type.NetAddr
	0, // 6: sesame.v1alpha1.RemoteControl.NetConn:input_type -> sesame.v1alpha1.NetConnRequest
	1, // 7: sesame.v1alpha1.RemoteControl.NetConn:output_type -> sesame.v1alpha1.NetConnResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sesame_v1alpha1_remotecontrol_proto_init() }
func file_sesame_v1alpha1_remotecontrol_proto_init() {
	if File_sesame_v1alpha1_remotecontrol_proto != nil {
		return
	}
	file_sesame_v1alpha1_remotecontrol_proto_msgTypes[0].OneofWrappers = []any{
		(*NetConnRequest_Dial_)(nil),
		(*NetConnRequest_Bytes)(nil),
	}
	file_sesame_v1alpha1_remotecontrol_proto_msgTypes[1].OneofWrappers = []any{
		(*NetConnResponse_Conn_)(nil),
		(*NetConnResponse_Bytes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sesame_v1alpha1_remotecontrol_proto_rawDesc), len(file_sesame_v1alpha1_remotecontrol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sesame_v1alpha1_remotecontrol_proto_goTypes,
		DependencyIndexes: file_sesame_v1alpha1_remotecontrol_proto_depIdxs,
		MessageInfos:      file_sesame_v1alpha1_remotecontrol_proto_msgTypes,
	}.Build()
	File_sesame_v1alpha1_remotecontrol_proto = out.File
	file_sesame_v1alpha1_remotecontrol_proto_goTypes = nil
	file_sesame_v1alpha1_remotecontrol_proto_depIdxs = nil
}
