// Code generated by protoc-gen-go-copy. DO NOT EDIT.
// source: sesame/type/netaddr.proto

package netaddr

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
func (x *NetAddr) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *NetAddr:
		x.Network = v.GetNetwork()
		x.Address = v.GetAddress()
	default:
		if v, ok := v.(interface{ GetNetwork() string }); ok {
			x.Network = v.GetNetwork()
		}
		if v, ok := v.(interface{ GetAddress() string }); ok {
			x.Address = v.GetAddress()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *NetAddr) Proto_ShallowClone() (c *NetAddr) {
	if x != nil {
		c = new(NetAddr)
		c.Network = x.Network
		c.Address = x.Address
	}
	return
}
