// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: sesame/tls/v1alpha1/tls.proto

package tls

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TLSVersion int32

const (
	TLSVersion_TLS_VERSION_UNSPECIFIED TLSVersion = 0
	TLSVersion_TLS_1_0                 TLSVersion = 1
	TLSVersion_TLS_1_1                 TLSVersion = 2
	TLSVersion_TLS_1_2                 TLSVersion = 3
	TLSVersion_TLS_1_3                 TLSVersion = 4
)

// Enum value maps for TLSVersion.
var (
	TLSVersion_name = map[int32]string{
		0: "TLS_VERSION_UNSPECIFIED",
		1: "TLS_1_0",
		2: "TLS_1_1",
		3: "TLS_1_2",
		4: "TLS_1_3",
	}
	TLSVersion_value = map[string]int32{
		"TLS_VERSION_UNSPECIFIED": 0,
		"TLS_1_0":                 1,
		"TLS_1_1":                 2,
		"TLS_1_2":                 3,
		"TLS_1_3":                 4,
	}
)

func (x TLSVersion) Enum() *TLSVersion {
	p := new(TLSVersion)
	*p = x
	return p
}

func (x TLSVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TLSVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_sesame_tls_v1alpha1_tls_proto_enumTypes[0].Descriptor()
}

func (TLSVersion) Type() protoreflect.EnumType {
	return &file_sesame_tls_v1alpha1_tls_proto_enumTypes[0]
}

func (x TLSVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TLSVersion.Descriptor instead.
func (TLSVersion) EnumDescriptor() ([]byte, []int) {
	return file_sesame_tls_v1alpha1_tls_proto_rawDescGZIP(), []int{0}
}

// FingerprintPreset specifies well-known client cryptographic signatures.
type FingerprintPreset int32

const (
	FingerprintPreset_FINGERPRINT_PRESET_UNSPECIFIED FingerprintPreset = 0
	// Chromium-based presets
	FingerprintPreset_CHROME_AUTO FingerprintPreset = 1
	FingerprintPreset_CHROME_120  FingerprintPreset = 2
	FingerprintPreset_CHROME_124  FingerprintPreset = 3
	FingerprintPreset_CHROME_131  FingerprintPreset = 4
	// Firefox-based presets
	FingerprintPreset_FIREFOX_AUTO FingerprintPreset = 10
	FingerprintPreset_FIREFOX_120  FingerprintPreset = 11
	// Safari / WebKit presets
	FingerprintPreset_SAFARI_AUTO FingerprintPreset = 20
	FingerprintPreset_SAFARI_16   FingerprintPreset = 21
	FingerprintPreset_SAFARI_17   FingerprintPreset = 22
	// Mobile client presets
	FingerprintPreset_IOS_AUTO       FingerprintPreset = 30
	FingerprintPreset_IOS_16         FingerprintPreset = 31
	FingerprintPreset_ANDROID_OKHTTP FingerprintPreset = 35
	// Standard runtime default (Go crypto/tls or Bun BoringSSL)
	FingerprintPreset_RUNTIME_DEFAULT FingerprintPreset = 40
)

// Enum value maps for FingerprintPreset.
var (
	FingerprintPreset_name = map[int32]string{
		0:  "FINGERPRINT_PRESET_UNSPECIFIED",
		1:  "CHROME_AUTO",
		2:  "CHROME_120",
		3:  "CHROME_124",
		4:  "CHROME_131",
		10: "FIREFOX_AUTO",
		11: "FIREFOX_120",
		20: "SAFARI_AUTO",
		21: "SAFARI_16",
		22: "SAFARI_17",
		30: "IOS_AUTO",
		31: "IOS_16",
		35: "ANDROID_OKHTTP",
		40: "RUNTIME_DEFAULT",
	}
	FingerprintPreset_value = map[string]int32{
		"FINGERPRINT_PRESET_UNSPECIFIED": 0,
		"CHROME_AUTO":                    1,
		"CHROME_120":                     2,
		"CHROME_124":                     3,
		"CHROME_131":                     4,
		"FIREFOX_AUTO":                   10,
		"FIREFOX_120":                    11,
		"SAFARI_AUTO":                    20,
		"SAFARI_16":                      21,
		"SAFARI_17":                      22,
		"IOS_AUTO":                       30,
		"IOS_16":                         31,
		"ANDROID_OKHTTP":                 35,
		"RUNTIME_DEFAULT":                40,
	}
)

func (x FingerprintPreset) Enum() *FingerprintPreset {
	p := new(FingerprintPreset)
	*p = x
	return p
}

func (x FingerprintPreset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FingerprintPreset) Descriptor() protoreflect.EnumDescriptor {
	return file_sesame_tls_v1alpha1_tls_proto_enumTypes[1].Descriptor()
}

func (FingerprintPreset) Type() protoreflect.EnumType {
	return &file_sesame_tls_v1alpha1_tls_proto_enumTypes[1]
}

func (x FingerprintPreset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FingerprintPreset.Descriptor instead.
func (FingerprintPreset) EnumDescriptor() ([]byte, []int) {
	return file_sesame_tls_v1alpha1_tls_proto_rawDescGZIP(), []int{1}
}

// TLSOptions specifies parameters for endpoint-terminated TLS and fingerprint emulation.
type TLSOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server Name Indication (SNI) override. If omitted, the dial address hostname MUST be used.
	ServerName string `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	// Prioritized list of Application-Layer Protocol Negotiation (ALPN) protocol names.
	// Example: ["h2", "http/1.1"]
	// If empty, the implementation MUST NOT send an ALPN extension.
	AlpnProtocols []string `protobuf:"bytes,2,rep,name=alpn_protocols,json=alpnProtocols,proto3" json:"alpn_protocols,omitempty"`
	// Minimum TLS protocol version acceptable.
	MinVersion TLSVersion `protobuf:"varint,3,opt,name=min_version,json=minVersion,proto3,enum=sesame.tls.v1alpha1.TLSVersion" json:"min_version,omitempty"`
	// Maximum TLS protocol version acceptable.
	MaxVersion TLSVersion `protobuf:"varint,4,opt,name=max_version,json=maxVersion,proto3,enum=sesame.tls.v1alpha1.TLSVersion" json:"max_version,omitempty"`
	// Impersonation profile preset for client cryptographic emulation.
	// If set to anything other than RUNTIME_DEFAULT, the Server MUST fail closed if it cannot satisfy it.
	FingerprintPreset FingerprintPreset `protobuf:"varint,5,opt,name=fingerprint_preset,json=fingerprintPreset,proto3,enum=sesame.tls.v1alpha1.FingerprintPreset" json:"fingerprint_preset,omitempty"`
	// Explicit cipher suite identifiers (RFC numbers). If non-empty, overrides preset defaults.
	CipherSuites []uint32 `protobuf:"varint,6,rep,packed,name=cipher_suites,json=cipherSuites,proto3" json:"cipher_suites,omitempty"`
	// InsecureSkipVerify disables remote certificate verification.
	// MUST NOT be set in production environments unless explicitly requested by user configuration.
	InsecureSkipVerify bool `protobuf:"varint,7,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
	// Custom Root Certificate Authority certificates in PEM format.
	CaCertificates []byte `protobuf:"bytes,8,opt,name=ca_certificates,json=caCertificates,proto3" json:"ca_certificates,omitempty"`
	// Client certificate chain in PEM format (for mutual TLS / mTLS).
	ClientCertificate []byte `protobuf:"bytes,9,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"`
	// Client private key in PEM format (for mutual TLS / mTLS).
	ClientPrivateKey []byte `protobuf:"bytes,10,opt,name=client_private_key,json=clientPrivateKey,proto3" json:"client_private_key,omitempty"`
	// TLS 1.3 session resumption ticket or pre-shared key.
	SessionTicket []byte `protobuf:"bytes,11,opt,name=session_ticket,json=sessionTicket,proto3" json:"session_ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSOptions) Reset() {
	*x = TLSOptions{}
	mi := &file_sesame_tls_v1alpha1_tls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSOptions) ProtoMessage() {}

func (x *TLSOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_tls_v1alpha1_tls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSOptions.ProtoReflect.Descriptor instead.
func (*TLSOptions) Descriptor() ([]byte, []int) {
	return file_sesame_tls_v1alpha1_tls_proto_rawDescGZIP(), []int{0}
}

func (x *TLSOptions) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *TLSOptions) GetAlpnProtocols() []string {
	if x != nil {
		return x.AlpnProtocols
	}
	return nil
}

func (x *TLSOptions) GetMinVersion() TLSVersion {
	if x != nil {
		return x.MinVersion
	}
	return TLSVersion_TLS_VERSION_UNSPECIFIED
}

func (x *TLSOptions) GetMaxVersion() TLSVersion {
	if x != nil {
		return x.MaxVersion
	}
	return TLSVersion_TLS_VERSION_UNSPECIFIED
}

func (x *TLSOptions) GetFingerprintPreset() FingerprintPreset {
	if x != nil {
		return x.FingerprintPreset
	}
	return FingerprintPreset_FINGERPRINT_PRESET_UNSPECIFIED
}

func (x *TLSOptions) GetCipherSuites() []uint32 {
	if x != nil {
		return x.CipherSuites
	}
	return nil
}

func (x *TLSOptions) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

func (x *TLSOptions) GetCaCertificates() []byte {
	if x != nil {
		return x.CaCertificates
	}
	return nil
}

func (x *TLSOptions) GetClientCertificate() []byte {
	if x != nil {
		return x.ClientCertificate
	}
	return nil
}

func (x *TLSOptions) GetClientPrivateKey() []byte {
	if x != nil {
		return x.ClientPrivateKey
	}
	return nil
}

func (x *TLSOptions) GetSessionTicket() []byte {
	if x != nil {
		return x.SessionTicket
	}
	return nil
}

// TLSHandshakeResult communicates negotiated TLS session state back to the Client.
type TLSHandshakeResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ALPN protocol string selected by the upstream server (e.g., "h2" or "http/1.1").
	// The Client MUST inspect this field before generating Layer 7 payloads.
	NegotiatedProtocol string `protobuf:"bytes,1,opt,name=negotiated_protocol,json=negotiatedProtocol,proto3" json:"negotiated_protocol,omitempty"`
	// Negotiated cipher suite identifier (e.g. 0x1301 for TLS_AES_128_GCM_SHA256).
	CipherSuite uint32 `protobuf:"varint,2,opt,name=cipher_suite,json=cipherSuite,proto3" json:"cipher_suite,omitempty"`
	// Negotiated TLS version.
	TlsVersion TLSVersion `protobuf:"varint,3,opt,name=tls_version,json=tlsVersion,proto3,enum=sesame.tls.v1alpha1.TLSVersion" json:"tls_version,omitempty"`
	// Server Name Indication acknowledged by the upstream server.
	ServerName string `protobuf:"bytes,4,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	// Peer certificate chain presented by upstream, formatted as raw DER bytes.
	PeerCertificates [][]byte `protobuf:"bytes,5,rep,name=peer_certificates,json=peerCertificates,proto3" json:"peer_certificates,omitempty"`
	// New session ticket issued by upstream (if applicable).
	ResumptionTicket []byte `protobuf:"bytes,6,opt,name=resumption_ticket,json=resumptionTicket,proto3" json:"resumption_ticket,omitempty"`
	// The actual fingerprint preset enforced by the server.
	// The Client MUST verify that applied_preset matches the requested preset.
	AppliedPreset FingerprintPreset `protobuf:"varint,7,opt,name=applied_preset,json=appliedPreset,proto3,enum=sesame.tls.v1alpha1.FingerprintPreset" json:"applied_preset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSHandshakeResult) Reset() {
	*x = TLSHandshakeResult{}
	mi := &file_sesame_tls_v1alpha1_tls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSHandshakeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSHandshakeResult) ProtoMessage() {}

func (x *TLSHandshakeResult) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_tls_v1alpha1_tls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSHandshakeResult.ProtoReflect.Descriptor instead.
func (*TLSHandshakeResult) Descriptor() ([]byte, []int) {
	return file_sesame_tls_v1alpha1_tls_proto_rawDescGZIP(), []int{1}
}

func (x *TLSHandshakeResult) GetNegotiatedProtocol() string {
	if x != nil {
		return x.NegotiatedProtocol
	}
	return ""
}

func (x *TLSHandshakeResult) GetCipherSuite() uint32 {
	if x != nil {
		return x.CipherSuite
	}
	return 0
}

func (x *TLSHandshakeResult) GetTlsVersion() TLSVersion {
	if x != nil {
		return x.TlsVersion
	}
	return TLSVersion_TLS_VERSION_UNSPECIFIED
}

func (x *TLSHandshakeResult) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *TLSHandshakeResult) GetPeerCertificates() [][]byte {
	if x != nil {
		return x.PeerCertificates
	}
	return nil
}

func (x *TLSHandshakeResult) GetResumptionTicket() []byte {
	if x != nil {
		return x.ResumptionTicket
	}
	return nil
}

func (x *TLSHandshakeResult) GetAppliedPreset() FingerprintPreset {
	if x != nil {
		return x.AppliedPreset
	}
	return FingerprintPreset_FINGERPRINT_PRESET_UNSPECIFIED
}

var File_sesame_tls_v1alpha1_tls_proto protoreflect.FileDescriptor

const file_sesame_tls_v1alpha1_tls_proto_rawDesc = "" +
	"\n" +
	"\x1dsesame/tls/v1alpha1/tls.proto\x12\x13sesame.tls.v1alpha1\"\xb3\x04\n" +
	"\n" +
	"TLSOptions\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12%\n" +
	"\x0ealpn_protocols\x18\x02 \x03(\tR\ralpnProtocols\x12@\n" +
	"\vmin_version\x18\x03 \x01(\x0e2\x1f.sesame.tls.v1alpha1.TLSVersionR\n" +
	"minVersion\x12@\n" +
	"\vmax_version\x18\x04 \x01(\x0e2\x1f.sesame.tls.v1alpha1.TLSVersionR\n" +
	"maxVersion\x12U\n" +
	"\x12fingerprint_preset\x18\x05 \x01(\x0e2&.sesame.tls.v1alpha1.FingerprintPresetR\x11fingerprintPreset\x12#\n" +
	"\rcipher_suites\x18\x06 \x03(\rR\fcipherSuites\x120\n" +
	"\x14insecure_skip_verify\x18\a \x01(\bR\x12insecureSkipVerify\x12'\n" +
	"\x0fca_certificates\x18\b \x01(\fR\x0ecaCertificates\x12-\n" +
	"\x12client_certificate\x18\t \x01(\fR\x11clientCertificate\x12,\n" +
	"\x12client_private_key\x18\n" +
	" \x01(\fR\x10clientPrivateKey\x12%\n" +
	"\x0esession_ticket\x18\v \x01(\fR\rsessionTicket\"\xf4\x02\n" +
	"\x12TLSHandshakeResult\x12/\n" +
	"\x13negotiated_protocol\x18\x01 \x01(\tR\x12negotiatedProtocol\x12!\n" +
	"\fcipher_suite\x18\x02 \x01(\rR\vcipherSuite\x12@\n" +
	"\vtls_version\x18\x03 \x01(\x0e2\x1f.sesame.tls.v1alpha1.TLSVersionR\n" +
	"tlsVersion\x12\x1f\n" +
	"\vserver_name\x18\x04 \x01(\tR\n" +
	"serverName\x12+\n" +
	"\x11peer_certificates\x18\x05 \x03(\fR\x10peerCertificates\x12+\n" +
	"\x11resumption_ticket\x18\x06 \x01(\fR\x10resumptionTicket\x12M\n" +
	"\x0eapplied_preset\x18\a \x01(\x0e2&.sesame.tls.v1alpha1.FingerprintPresetR\rappliedPreset*]\n" +
	"\n" +
	"TLSVersion\x12\x1b\n" +
	"\x17TLS_VERSION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aTLS_1_0\x10\x01\x12\v\n" +
	"\aTLS_1_1\x10\x02\x12\v\n" +
	"\aTLS_1_2\x10\x03\x12\v\n" +
	"\aTLS_1_3\x10\x04*\x8d\x02\n" +
	"\x11FingerprintPreset\x12\"\n" +
	"\x1eFINGERPRINT_PRESET_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vCHROME_AUTO\x10\x01\x12\x0e\n" +
	"\n" +
	"CHROME_120\x10\x02\x12\x0e\n" +
	"\n" +
	"CHROME_124\x10\x03\x12\x0e\n" +
	"\n" +
	"CHROME_131\x10\x04\x12\x10\n" +
	"\fFIREFOX_AUTO\x10\n" +
	"\x12\x0f\n" +
	"\vFIREFOX_120\x10\v\x12\x0f\n" +
	"\vSAFARI_AUTO\x10\x14\x12\r\n" +
	"\tSAFARI_16\x10\x15\x12\r\n" +
	"\tSAFARI_17\x10\x16\x12\f\n" +
	"\bIOS_AUTO\x10\x1e\x12\n" +
	"\n" +
	"\x06IOS_16\x10\x1f\x12\x12\n" +
	"\x0eANDROID_OKHTTP\x10#\x12\x13\n" +
	"\x0fRUNTIME_DEFAULT\x10(B&Z$github.com/joeycumines/sesame/rc/tlsb\x06proto3"

var (
	file_sesame_tls_v1alpha1_tls_proto_rawDescOnce sync.Once
	file_sesame_tls_v1alpha1_tls_proto_rawDescData []byte
)

func file_sesame_tls_v1alpha1_tls_proto_rawDescGZIP() []byte {
	file_sesame_tls_v1alpha1_tls_proto_rawDescOnce.Do(func() {
		file_sesame_tls_v1alpha1_tls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sesame_tls_v1alpha1_tls_proto_rawDesc), len(file_sesame_tls_v1alpha1_tls_proto_rawDesc)))
	})
	return file_sesame_tls_v1alpha1_tls_proto_rawDescData
}

var file_sesame_tls_v1alpha1_tls_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sesame_tls_v1alpha1_tls_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sesame_tls_v1alpha1_tls_proto_goTypes = []any{
	(TLSVersion)(0),            // 0: sesame.tls.v1alpha1.TLSVersion
	(FingerprintPreset)(0),     // 1: sesame.tls.v1alpha1.FingerprintPreset
	(*TLSOptions)(nil),         // 2: sesame.tls.v1alpha1.TLSOptions
	(*TLSHandshakeResult)(nil), // 3: sesame.tls.v1alpha1.TLSHandshakeResult
}
var file_sesame_tls_v1alpha1_tls_proto_depIdxs = []int32{
	0, // 0: sesame.tls.v1alpha1.TLSOptions.min_version:type_name -> sesame.tls.v1alpha1.TLSVersion
	0, // 1: sesame.tls.v1alpha1.TLSOptions.max_version:type_name -> sesame.tls.v1alpha1.TLSVersion
	1, // 2: sesame.tls.v1alpha1.TLSOptions.fingerprint_preset:type_name -> sesame.tls.v1alpha1.FingerprintPreset
	0, // 3: sesame.tls.v1alpha1.TLSHandshakeResult.tls_version:type_name -> sesame.tls.v1alpha1.TLSVersion
	1, // 4: sesame.tls.v1alpha1.TLSHandshakeResult.applied_preset:type_name -> sesame.tls.v1alpha1.FingerprintPreset
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sesame_tls_v1alpha1_tls_proto_init() }
func file_sesame_tls_v1alpha1_tls_proto_init() {
	if File_sesame_tls_v1alpha1_tls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sesame_tls_v1alpha1_tls_proto_rawDesc), len(file_sesame_tls_v1alpha1_tls_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sesame_tls_v1alpha1_tls_proto_goTypes,
		DependencyIndexes: file_sesame_tls_v1alpha1_tls_proto_depIdxs,
		EnumInfos:         file_sesame_tls_v1alpha1_tls_proto_enumTypes,
		MessageInfos:      file_sesame_tls_v1alpha1_tls_proto_msgTypes,
	}.Build()
	File_sesame_tls_v1alpha1_tls_proto = out.File
	file_sesame_tls_v1alpha1_tls_proto_goTypes = nil
	file_sesame_tls_v1alpha1_tls_proto_depIdxs = nil
}
