// Code generated by protoc-gen-go-copy. DO NOT EDIT.
// source: sesame/v1alpha1/proxy.proto

package proxy

import "github.com/joeycumines/sesame/type/netaddr"

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *ProxyOptions) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *ProxyOptions:
		x.Hops = v.GetHops()
	default:
		if v, ok := v.(interface{ GetHops() []*ProxyHop }); ok {
			x.Hops = v.GetHops()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *ProxyOptions) Proto_ShallowClone() (c *ProxyOptions) {
	if x != nil {
		c = new(ProxyOptions)
		c.Hops = x.Hops
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *ProxyHop) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *ProxyHop:
		x.Type = v.GetType()
		x.Address = v.GetAddress()
		x.Username = v.GetUsername()
		x.Password = v.GetPassword()
		x.AuthHeader = v.GetAuthHeader()
	default:
		if v, ok := v.(interface{ GetType() ProxyHop_Type }); ok {
			x.Type = v.GetType()
		}
		if v, ok := v.(interface{ GetAddress() *netaddr.NetAddr }); ok {
			x.Address = v.GetAddress()
		}
		if v, ok := v.(interface{ GetUsername() string }); ok {
			x.Username = v.GetUsername()
		}
		if v, ok := v.(interface{ GetPassword() string }); ok {
			x.Password = v.GetPassword()
		}
		if v, ok := v.(interface{ GetAuthHeader() string }); ok {
			x.AuthHeader = v.GetAuthHeader()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *ProxyHop) Proto_ShallowClone() (c *ProxyHop) {
	if x != nil {
		c = new(ProxyHop)
		c.Type = x.Type
		c.Address = x.Address
		c.Username = x.Username
		c.Password = x.Password
		c.AuthHeader = x.AuthHeader
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *ProxyResult) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *ProxyResult:
		x.TraversedHops = v.GetTraversedHops()
		x.EgressAddress = v.GetEgressAddress()
	default:
		if v, ok := v.(interface{ GetTraversedHops() []*netaddr.NetAddr }); ok {
			x.TraversedHops = v.GetTraversedHops()
		}
		if v, ok := v.(interface{ GetEgressAddress() *netaddr.NetAddr }); ok {
			x.EgressAddress = v.GetEgressAddress()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *ProxyResult) Proto_ShallowClone() (c *ProxyResult) {
	if x != nil {
		c = new(ProxyResult)
		c.TraversedHops = x.TraversedHops
		c.EgressAddress = x.EgressAddress
	}
	return
}
