// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: sesame/v1alpha1/sesame.proto

package api

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	grpcmetadata "github.com/joeycumines/sesame/type/grpcmetadata"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Remote is a network device or other resource that may be accessed by Sesame clients.
type Remote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Remote) Reset() {
	*x = Remote{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Remote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remote) ProtoMessage() {}

func (x *Remote) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remote.ProtoReflect.Descriptor instead.
func (*Remote) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{0}
}

func (x *Remote) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Remote) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Remote) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Remote) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

// Endpoint is a gRPC service available via a remote.
type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Spec          *Endpoint_Spec         `protobuf:"bytes,11,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{1}
}

func (x *Endpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Endpoint) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Endpoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Endpoint) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Endpoint) GetSpec() *Endpoint_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// Namespace scopes resources in the Sesame API, and is intended to (eventually) facilitate scoped simple auth.
type Namespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{2}
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateRemoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the parent Namespace, note that remote.name MUST NOT be set.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// May be specified to request a specific (non-trailing) resource id, note it's a single path segment, w/o any "/".
	ResourceId    string  `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Remote        *Remote `protobuf:"bytes,11,opt,name=remote,proto3" json:"remote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRemoteRequest) Reset() {
	*x = CreateRemoteRequest{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRemoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRemoteRequest) ProtoMessage() {}

func (x *CreateRemoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRemoteRequest.ProtoReflect.Descriptor instead.
func (*CreateRemoteRequest) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRemoteRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateRemoteRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CreateRemoteRequest) GetRemote() *Remote {
	if x != nil {
		return x.Remote
	}
	return nil
}

type GetRemoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRemoteRequest) Reset() {
	*x = GetRemoteRequest{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRemoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRemoteRequest) ProtoMessage() {}

func (x *GetRemoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRemoteRequest.ProtoReflect.Descriptor instead.
func (*GetRemoteRequest) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{4}
}

func (x *GetRemoteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteRemoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRemoteRequest) Reset() {
	*x = DeleteRemoteRequest{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRemoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRemoteRequest) ProtoMessage() {}

func (x *DeleteRemoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRemoteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRemoteRequest) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRemoteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateRemoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	Remote        *Remote                `protobuf:"bytes,11,opt,name=remote,proto3" json:"remote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRemoteRequest) Reset() {
	*x = UpdateRemoteRequest{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRemoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRemoteRequest) ProtoMessage() {}

func (x *UpdateRemoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRemoteRequest.ProtoReflect.Descriptor instead.
func (*UpdateRemoteRequest) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRemoteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRemoteRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateRemoteRequest) GetRemote() *Remote {
	if x != nil {
		return x.Remote
	}
	return nil
}

type ListRemotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRemotesRequest) Reset() {
	*x = ListRemotesRequest{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemotesRequest) ProtoMessage() {}

func (x *ListRemotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemotesRequest.ProtoReflect.Descriptor instead.
func (*ListRemotesRequest) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{7}
}

func (x *ListRemotesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListRemotesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRemotesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListRemotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Remotes       []*Remote              `protobuf:"bytes,1,rep,name=remotes,proto3" json:"remotes,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRemotesResponse) Reset() {
	*x = ListRemotesResponse{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemotesResponse) ProtoMessage() {}

func (x *ListRemotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemotesResponse.ProtoReflect.Descriptor instead.
func (*ListRemotesResponse) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{8}
}

func (x *ListRemotesResponse) GetRemotes() []*Remote {
	if x != nil {
		return x.Remotes
	}
	return nil
}

func (x *ListRemotesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateEndpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the parent Remote, note that endpoint.name MUST NOT be set.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// May be specified to request a specific (non-trailing) resource id, note it's a single path segment, w/o any "/".
	ResourceId    string    `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Endpoint      *Endpoint `protobuf:"bytes,11,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEndpointRequest) Reset() {
	*x = CreateEndpointRequest{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEndpointRequest) ProtoMessage() {}

func (x *CreateEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEndpointRequest.ProtoReflect.Descriptor instead.
func (*CreateEndpointRequest) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{9}
}

func (x *CreateEndpointRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateEndpointRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CreateEndpointRequest) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type GetEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointRequest) Reset() {
	*x = GetEndpointRequest{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointRequest) ProtoMessage() {}

func (x *GetEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointRequest.ProtoReflect.Descriptor instead.
func (*GetEndpointRequest) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{10}
}

func (x *GetEndpointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEndpointRequest) Reset() {
	*x = DeleteEndpointRequest{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEndpointRequest) ProtoMessage() {}

func (x *DeleteEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEndpointRequest.ProtoReflect.Descriptor instead.
func (*DeleteEndpointRequest) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteEndpointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateEndpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	Endpoint      *Endpoint              `protobuf:"bytes,11,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEndpointRequest) Reset() {
	*x = UpdateEndpointRequest{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEndpointRequest) ProtoMessage() {}

func (x *UpdateEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEndpointRequest.ProtoReflect.Descriptor instead.
func (*UpdateEndpointRequest) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateEndpointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEndpointRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateEndpointRequest) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type ListEndpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpointsRequest) Reset() {
	*x = ListEndpointsRequest{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsRequest) ProtoMessage() {}

func (x *ListEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsRequest.ProtoReflect.Descriptor instead.
func (*ListEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{13}
}

func (x *ListEndpointsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListEndpointsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEndpointsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListEndpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*Endpoint            `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpointsResponse) Reset() {
	*x = ListEndpointsResponse{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsResponse) ProtoMessage() {}

func (x *ListEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsResponse.ProtoReflect.Descriptor instead.
func (*ListEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{14}
}

func (x *ListEndpointsResponse) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *ListEndpointsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ProxyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ProxyRequest_Dial_
	//	*ProxyRequest_Header
	//	*ProxyRequest_Content
	Data          isProxyRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest.ProtoReflect.Descriptor instead.
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{15}
}

func (x *ProxyRequest) GetData() isProxyRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProxyRequest) GetDial() *ProxyRequest_Dial {
	if x != nil {
		if x, ok := x.Data.(*ProxyRequest_Dial_); ok {
			return x.Dial
		}
	}
	return nil
}

func (x *ProxyRequest) GetHeader() *grpcmetadata.GrpcMetadata {
	if x != nil {
		if x, ok := x.Data.(*ProxyRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *ProxyRequest) GetContent() *anypb.Any {
	if x != nil {
		if x, ok := x.Data.(*ProxyRequest_Content); ok {
			return x.Content
		}
	}
	return nil
}

type isProxyRequest_Data interface {
	isProxyRequest_Data()
}

type ProxyRequest_Dial_ struct {
	Dial *ProxyRequest_Dial `protobuf:"bytes,1,opt,name=dial,proto3,oneof"`
}

type ProxyRequest_Header struct {
	Header *grpcmetadata.GrpcMetadata `protobuf:"bytes,2,opt,name=header,proto3,oneof"`
}

type ProxyRequest_Content struct {
	Content *anypb.Any `protobuf:"bytes,3,opt,name=content,proto3,oneof"`
}

func (*ProxyRequest_Dial_) isProxyRequest_Data() {}

func (*ProxyRequest_Header) isProxyRequest_Data() {}

func (*ProxyRequest_Content) isProxyRequest_Data() {}

type ProxyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ProxyResponse_Conn_
	//	*ProxyResponse_Error
	//	*ProxyResponse_Header
	//	*ProxyResponse_Content
	//	*ProxyResponse_Trailer
	Data          isProxyResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponse) Reset() {
	*x = ProxyResponse{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse) ProtoMessage() {}

func (x *ProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponse.ProtoReflect.Descriptor instead.
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{16}
}

func (x *ProxyResponse) GetData() isProxyResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProxyResponse) GetConn() *ProxyResponse_Conn {
	if x != nil {
		if x, ok := x.Data.(*ProxyResponse_Conn_); ok {
			return x.Conn
		}
	}
	return nil
}

func (x *ProxyResponse) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Data.(*ProxyResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ProxyResponse) GetHeader() *grpcmetadata.GrpcMetadata {
	if x != nil {
		if x, ok := x.Data.(*ProxyResponse_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *ProxyResponse) GetContent() *anypb.Any {
	if x != nil {
		if x, ok := x.Data.(*ProxyResponse_Content); ok {
			return x.Content
		}
	}
	return nil
}

func (x *ProxyResponse) GetTrailer() *grpcmetadata.GrpcMetadata {
	if x != nil {
		if x, ok := x.Data.(*ProxyResponse_Trailer); ok {
			return x.Trailer
		}
	}
	return nil
}

type isProxyResponse_Data interface {
	isProxyResponse_Data()
}

type ProxyResponse_Conn_ struct {
	Conn *ProxyResponse_Conn `protobuf:"bytes,1,opt,name=conn,proto3,oneof"`
}

type ProxyResponse_Error struct {
	// error models an error from the inner call, and may be received any time after conn
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type ProxyResponse_Header struct {
	Header *grpcmetadata.GrpcMetadata `protobuf:"bytes,3,opt,name=header,proto3,oneof"`
}

type ProxyResponse_Content struct {
	Content *anypb.Any `protobuf:"bytes,4,opt,name=content,proto3,oneof"`
}

type ProxyResponse_Trailer struct {
	Trailer *grpcmetadata.GrpcMetadata `protobuf:"bytes,5,opt,name=trailer,proto3,oneof"`
}

func (*ProxyResponse_Conn_) isProxyResponse_Data() {}

func (*ProxyResponse_Error) isProxyResponse_Data() {}

func (*ProxyResponse_Header) isProxyResponse_Data() {}

func (*ProxyResponse_Content) isProxyResponse_Data() {}

func (*ProxyResponse_Trailer) isProxyResponse_Data() {}

// Spec models the endpoint specification, containing configuration around access and usage behavior.
type Endpoint_Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*Endpoint_Spec_Tunnel
	Data          isEndpoint_Spec_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint_Spec) Reset() {
	*x = Endpoint_Spec{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint_Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint_Spec) ProtoMessage() {}

func (x *Endpoint_Spec) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint_Spec.ProtoReflect.Descriptor instead.
func (*Endpoint_Spec) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Endpoint_Spec) GetData() isEndpoint_Spec_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Endpoint_Spec) GetTunnel() *Endpoint_Tunnel {
	if x != nil {
		if x, ok := x.Data.(*Endpoint_Spec_Tunnel); ok {
			return x.Tunnel
		}
	}
	return nil
}

type isEndpoint_Spec_Data interface {
	isEndpoint_Spec_Data()
}

type Endpoint_Spec_Tunnel struct {
	Tunnel *Endpoint_Tunnel `protobuf:"bytes,1,opt,name=tunnel,proto3,oneof"`
}

func (*Endpoint_Spec_Tunnel) isEndpoint_Spec_Data() {}

// Tunnel models an endpoint exposed directly over a tunnel provider.
type Endpoint_Tunnel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint_Tunnel) Reset() {
	*x = Endpoint_Tunnel{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint_Tunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint_Tunnel) ProtoMessage() {}

func (x *Endpoint_Tunnel) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint_Tunnel.ProtoReflect.Descriptor instead.
func (*Endpoint_Tunnel) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{1, 1}
}

// Dial models the initial request routing of a method call.
type ProxyRequest_Dial struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Endpoint string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Method   string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// conn_mask is an optional field mask for ProxyResponse.conn.
	ConnMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=conn_mask,json=connMask,proto3" json:"conn_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequest_Dial) Reset() {
	*x = ProxyRequest_Dial{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest_Dial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest_Dial) ProtoMessage() {}

func (x *ProxyRequest_Dial) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest_Dial.ProtoReflect.Descriptor instead.
func (*ProxyRequest_Dial) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{15, 0}
}

func (x *ProxyRequest_Dial) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ProxyRequest_Dial) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProxyRequest_Dial) GetConnMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ConnMask
	}
	return nil
}

// Conn is the response to ProxyRequest.dial.
type ProxyResponse_Conn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *Namespace             `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Remote        *Remote                `protobuf:"bytes,2,opt,name=remote,proto3" json:"remote,omitempty"`
	Endpoint      *Endpoint              `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponse_Conn) Reset() {
	*x = ProxyResponse_Conn{}
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse_Conn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse_Conn) ProtoMessage() {}

func (x *ProxyResponse_Conn) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_v1alpha1_sesame_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponse_Conn.ProtoReflect.Descriptor instead.
func (*ProxyResponse_Conn) Descriptor() ([]byte, []int) {
	return file_sesame_v1alpha1_sesame_proto_rawDescGZIP(), []int{16, 0}
}

func (x *ProxyResponse_Conn) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *ProxyResponse_Conn) GetRemote() *Remote {
	if x != nil {
		return x.Remote
	}
	return nil
}

func (x *ProxyResponse_Conn) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

var File_sesame_v1alpha1_sesame_proto protoreflect.FileDescriptor

const file_sesame_v1alpha1_sesame_proto_rawDesc = "" +
	"\n" +
	"\x1csesame/v1alpha1/sesame.proto\x12\x0fsesame.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x19google/protobuf/any.proto\x1a\x17google/rpc/status.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1esesame/type/grpcmetadata.proto\"\xa8\x01\n" +
	"\x06Remote\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12@\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\"\xb4\x02\n" +
	"\bEndpoint\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12@\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x122\n" +
	"\x04spec\x18\v \x01(\v2\x1e.sesame.v1alpha1.Endpoint.SpecR\x04spec\x1aJ\n" +
	"\x04Spec\x12:\n" +
	"\x06tunnel\x18\x01 \x01(\v2 .sesame.v1alpha1.Endpoint.TunnelH\x00R\x06tunnelB\x06\n" +
	"\x04data\x1a\b\n" +
	"\x06Tunnel\"$\n" +
	"\tNamespace\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\"\x7f\n" +
	"\x13CreateRemoteRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12/\n" +
	"\x06remote\x18\v \x01(\v2\x17.sesame.v1alpha1.RemoteR\x06remote\"&\n" +
	"\x10GetRemoteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\x13DeleteRemoteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x97\x01\n" +
	"\x13UpdateRemoteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12/\n" +
	"\x06remote\x18\v \x01(\v2\x17.sesame.v1alpha1.RemoteR\x06remote\"h\n" +
	"\x12ListRemotesRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"p\n" +
	"\x13ListRemotesResponse\x121\n" +
	"\aremotes\x18\x01 \x03(\v2\x17.sesame.v1alpha1.RemoteR\aremotes\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x87\x01\n" +
	"\x15CreateEndpointRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x125\n" +
	"\bendpoint\x18\v \x01(\v2\x19.sesame.v1alpha1.EndpointR\bendpoint\"(\n" +
	"\x12GetEndpointRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\x15DeleteEndpointRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x9f\x01\n" +
	"\x15UpdateEndpointRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x125\n" +
	"\bendpoint\x18\v \x01(\v2\x19.sesame.v1alpha1.EndpointR\bendpoint\"j\n" +
	"\x14ListEndpointsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"x\n" +
	"\x15ListEndpointsResponse\x127\n" +
	"\tendpoints\x18\x01 \x03(\v2\x19.sesame.v1alpha1.EndpointR\tendpoints\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xac\x02\n" +
	"\fProxyRequest\x128\n" +
	"\x04dial\x18\x01 \x01(\v2\".sesame.v1alpha1.ProxyRequest.DialH\x00R\x04dial\x123\n" +
	"\x06header\x18\x02 \x01(\v2\x19.sesame.type.GrpcMetadataH\x00R\x06header\x120\n" +
	"\acontent\x18\x03 \x01(\v2\x14.google.protobuf.AnyH\x00R\acontent\x1as\n" +
	"\x04Dial\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x127\n" +
	"\tconn_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\bconnMaskB\x06\n" +
	"\x04data\"\xc7\x03\n" +
	"\rProxyResponse\x129\n" +
	"\x04conn\x18\x01 \x01(\v2#.sesame.v1alpha1.ProxyResponse.ConnH\x00R\x04conn\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.google.rpc.StatusH\x00R\x05error\x123\n" +
	"\x06header\x18\x03 \x01(\v2\x19.sesame.type.GrpcMetadataH\x00R\x06header\x120\n" +
	"\acontent\x18\x04 \x01(\v2\x14.google.protobuf.AnyH\x00R\acontent\x125\n" +
	"\atrailer\x18\x05 \x01(\v2\x19.sesame.type.GrpcMetadataH\x00R\atrailer\x1a\xa8\x01\n" +
	"\x04Conn\x128\n" +
	"\tnamespace\x18\x01 \x01(\v2\x1a.sesame.v1alpha1.NamespaceR\tnamespace\x12/\n" +
	"\x06remote\x18\x02 \x01(\v2\x17.sesame.v1alpha1.RemoteR\x06remote\x125\n" +
	"\bendpoint\x18\x03 \x01(\v2\x19.sesame.v1alpha1.EndpointR\bendpointB\x06\n" +
	"\x04data2\xfc\v\n" +
	"\x06Sesame\x12\x86\x01\n" +
	"\fCreateRemote\x12$.sesame.v1alpha1.CreateRemoteRequest\x1a\x17.sesame.v1alpha1.Remote\"7\x82\xd3\xe4\x93\x021:\x06remote\"'/v1alpha1/{parent=namespaces/*}/remotes\x12x\n" +
	"\tGetRemote\x12!.sesame.v1alpha1.GetRemoteRequest\x1a\x17.sesame.v1alpha1.Remote\"/\x82\xd3\xe4\x93\x02)\x12'/v1alpha1/{name=namespaces/*/remotes/*}\x12}\n" +
	"\fDeleteRemote\x12$.sesame.v1alpha1.DeleteRemoteRequest\x1a\x16.google.protobuf.Empty\"/\x82\xd3\xe4\x93\x02)*'/v1alpha1/{name=namespaces/*/remotes/*}\x12\x86\x01\n" +
	"\fUpdateRemote\x12$.sesame.v1alpha1.UpdateRemoteRequest\x1a\x17.sesame.v1alpha1.Remote\"7\x82\xd3\xe4\x93\x021:\x06remote2'/v1alpha1/{name=namespaces/*/remotes/*}\x12\x89\x01\n" +
	"\vListRemotes\x12#.sesame.v1alpha1.ListRemotesRequest\x1a$.sesame.v1alpha1.ListRemotesResponse\"/\x82\xd3\xe4\x93\x02)\x12'/v1alpha1/{parent=namespaces/*}/remotes\x12\x9a\x01\n" +
	"\x0eCreateEndpoint\x12&.sesame.v1alpha1.CreateEndpointRequest\x1a\x19.sesame.v1alpha1.Endpoint\"E\x82\xd3\xe4\x93\x02?:\bendpoint\"3/v1alpha1/{parent=namespaces/*/remotes/*}/endpoints\x12\x8a\x01\n" +
	"\vGetEndpoint\x12#.sesame.v1alpha1.GetEndpointRequest\x1a\x19.sesame.v1alpha1.Endpoint\";\x82\xd3\xe4\x93\x025\x123/v1alpha1/{name=namespaces/*/remotes/*/endpoints/*}\x12\x8d\x01\n" +
	"\x0eDeleteEndpoint\x12&.sesame.v1alpha1.DeleteEndpointRequest\x1a\x16.google.protobuf.Empty\";\x82\xd3\xe4\x93\x025*3/v1alpha1/{name=namespaces/*/remotes/*/endpoints/*}\x12\x9a\x01\n" +
	"\x0eUpdateEndpoint\x12&.sesame.v1alpha1.UpdateEndpointRequest\x1a\x19.sesame.v1alpha1.Endpoint\"E\x82\xd3\xe4\x93\x02?:\bendpoint23/v1alpha1/{name=namespaces/*/remotes/*/endpoints/*}\x12\x9b\x01\n" +
	"\rListEndpoints\x12%.sesame.v1alpha1.ListEndpointsRequest\x1a&.sesame.v1alpha1.ListEndpointsResponse\";\x82\xd3\xe4\x93\x025\x123/v1alpha1/{parent=namespaces/*/remotes/*}/endpoints\x12f\n" +
	"\x05Proxy\x12\x1d.sesame.v1alpha1.ProxyRequest\x1a\x1e.sesame.v1alpha1.ProxyResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1alpha1/proxy(\x010\x01B\x9e\x02\x92A\xf7\x01\x12\x8f\x01\"7\n" +
	"\x0eSesame project\x12%https://github.com/joeycumines/sesame*F\n" +
	"\vMIT License\x127https://github.com/joeycumines/sesame/blob/main/LICENSE2\f0.1.0-alpha1*\x03\x01\x02\x042\x10application/json:\x10application/jsonr:\n" +
	"\x11Source repository\x12%https://github.com/joeycumines/sesameZ!github.com/joeycumines/sesame/apib\x06proto3"

var (
	file_sesame_v1alpha1_sesame_proto_rawDescOnce sync.Once
	file_sesame_v1alpha1_sesame_proto_rawDescData []byte
)

func file_sesame_v1alpha1_sesame_proto_rawDescGZIP() []byte {
	file_sesame_v1alpha1_sesame_proto_rawDescOnce.Do(func() {
		file_sesame_v1alpha1_sesame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sesame_v1alpha1_sesame_proto_rawDesc), len(file_sesame_v1alpha1_sesame_proto_rawDesc)))
	})
	return file_sesame_v1alpha1_sesame_proto_rawDescData
}

var file_sesame_v1alpha1_sesame_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_sesame_v1alpha1_sesame_proto_goTypes = []any{
	(*Remote)(nil),                    // 0: sesame.v1alpha1.Remote
	(*Endpoint)(nil),                  // 1: sesame.v1alpha1.Endpoint
	(*Namespace)(nil),                 // 2: sesame.v1alpha1.Namespace
	(*CreateRemoteRequest)(nil),       // 3: sesame.v1alpha1.CreateRemoteRequest
	(*GetRemoteRequest)(nil),          // 4: sesame.v1alpha1.GetRemoteRequest
	(*DeleteRemoteRequest)(nil),       // 5: sesame.v1alpha1.DeleteRemoteRequest
	(*UpdateRemoteRequest)(nil),       // 6: sesame.v1alpha1.UpdateRemoteRequest
	(*ListRemotesRequest)(nil),        // 7: sesame.v1alpha1.ListRemotesRequest
	(*ListRemotesResponse)(nil),       // 8: sesame.v1alpha1.ListRemotesResponse
	(*CreateEndpointRequest)(nil),     // 9: sesame.v1alpha1.CreateEndpointRequest
	(*GetEndpointRequest)(nil),        // 10: sesame.v1alpha1.GetEndpointRequest
	(*DeleteEndpointRequest)(nil),     // 11: sesame.v1alpha1.DeleteEndpointRequest
	(*UpdateEndpointRequest)(nil),     // 12: sesame.v1alpha1.UpdateEndpointRequest
	(*ListEndpointsRequest)(nil),      // 13: sesame.v1alpha1.ListEndpointsRequest
	(*ListEndpointsResponse)(nil),     // 14: sesame.v1alpha1.ListEndpointsResponse
	(*ProxyRequest)(nil),              // 15: sesame.v1alpha1.ProxyRequest
	(*ProxyResponse)(nil),             // 16: sesame.v1alpha1.ProxyResponse
	(*Endpoint_Spec)(nil),             // 17: sesame.v1alpha1.Endpoint.Spec
	(*Endpoint_Tunnel)(nil),           // 18: sesame.v1alpha1.Endpoint.Tunnel
	(*ProxyRequest_Dial)(nil),         // 19: sesame.v1alpha1.ProxyRequest.Dial
	(*ProxyResponse_Conn)(nil),        // 20: sesame.v1alpha1.ProxyResponse.Conn
	(*timestamppb.Timestamp)(nil),     // 21: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),     // 22: google.protobuf.FieldMask
	(*grpcmetadata.GrpcMetadata)(nil), // 23: sesame.type.GrpcMetadata
	(*anypb.Any)(nil),                 // 24: google.protobuf.Any
	(*status.Status)(nil),             // 25: google.rpc.Status
	(*emptypb.Empty)(nil),             // 26: google.protobuf.Empty
}
var file_sesame_v1alpha1_sesame_proto_depIdxs = []int32{
	21, // 0: sesame.v1alpha1.Remote.create_time:type_name -> google.protobuf.Timestamp
	21, // 1: sesame.v1alpha1.Endpoint.create_time:type_name -> google.protobuf.Timestamp
	17, // 2: sesame.v1alpha1.Endpoint.spec:type_name -> sesame.v1alpha1.Endpoint.Spec
	0,  // 3: sesame.v1alpha1.CreateRemoteRequest.remote:type_name -> sesame.v1alpha1.Remote
	22, // 4: sesame.v1alpha1.UpdateRemoteRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 5: sesame.v1alpha1.UpdateRemoteRequest.remote:type_name -> sesame.v1alpha1.Remote
	0,  // 6: sesame.v1alpha1.ListRemotesResponse.remotes:type_name -> sesame.v1alpha1.Remote
	1,  // 7: sesame.v1alpha1.CreateEndpointRequest.endpoint:type_name -> sesame.v1alpha1.Endpoint
	22, // 8: sesame.v1alpha1.UpdateEndpointRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 9: sesame.v1alpha1.UpdateEndpointRequest.endpoint:type_name -> sesame.v1alpha1.Endpoint
	1,  // 10: sesame.v1alpha1.ListEndpointsResponse.endpoints:type_name -> sesame.v1alpha1.Endpoint
	19, // 11: sesame.v1alpha1.ProxyRequest.dial:type_name -> sesame.v1alpha1.ProxyRequest.Dial
	23, // 12: sesame.v1alpha1.ProxyRequest.header:type_name -> sesame.type.GrpcMetadata
	24, // 13: sesame.v1alpha1.ProxyRequest.content:type_name -> google.protobuf.Any
	20, // 14: sesame.v1alpha1.ProxyResponse.conn:type_name -> sesame.v1alpha1.ProxyResponse.Conn
	25, // 15: sesame.v1alpha1.ProxyResponse.error:type_name -> google.rpc.Status
	23, // 16: sesame.v1alpha1.ProxyResponse.header:type_name -> sesame.type.GrpcMetadata
	24, // 17: sesame.v1alpha1.ProxyResponse.content:type_name -> google.protobuf.Any
	23, // 18: sesame.v1alpha1.ProxyResponse.trailer:type_name -> sesame.type.GrpcMetadata
	18, // 19: sesame.v1alpha1.Endpoint.Spec.tunnel:type_name -> sesame.v1alpha1.Endpoint.Tunnel
	22, // 20: sesame.v1alpha1.ProxyRequest.Dial.conn_mask:type_name -> google.protobuf.FieldMask
	2,  // 21: sesame.v1alpha1.ProxyResponse.Conn.namespace:type_name -> sesame.v1alpha1.Namespace
	0,  // 22: sesame.v1alpha1.ProxyResponse.Conn.remote:type_name -> sesame.v1alpha1.Remote
	1,  // 23: sesame.v1alpha1.ProxyResponse.Conn.endpoint:type_name -> sesame.v1alpha1.Endpoint
	3,  // 24: sesame.v1alpha1.Sesame.CreateRemote:input_type -> sesame.v1alpha1.CreateRemoteRequest
	4,  // 25: sesame.v1alpha1.Sesame.GetRemote:input_type -> sesame.v1alpha1.GetRemoteRequest
	5,  // 26: sesame.v1alpha1.Sesame.DeleteRemote:input_type -> sesame.v1alpha1.DeleteRemoteRequest
	6,  // 27: sesame.v1alpha1.Sesame.UpdateRemote:input_type -> sesame.v1alpha1.UpdateRemoteRequest
	7,  // 28: sesame.v1alpha1.Sesame.ListRemotes:input_type -> sesame.v1alpha1.ListRemotesRequest
	9,  // 29: sesame.v1alpha1.Sesame.CreateEndpoint:input_type -> sesame.v1alpha1.CreateEndpointRequest
	10, // 30: sesame.v1alpha1.Sesame.GetEndpoint:input_type -> sesame.v1alpha1.GetEndpointRequest
	11, // 31: sesame.v1alpha1.Sesame.DeleteEndpoint:input_type -> sesame.v1alpha1.DeleteEndpointRequest
	12, // 32: sesame.v1alpha1.Sesame.UpdateEndpoint:input_type -> sesame.v1alpha1.UpdateEndpointRequest
	13, // 33: sesame.v1alpha1.Sesame.ListEndpoints:input_type -> sesame.v1alpha1.ListEndpointsRequest
	15, // 34: sesame.v1alpha1.Sesame.Proxy:input_type -> sesame.v1alpha1.ProxyRequest
	0,  // 35: sesame.v1alpha1.Sesame.CreateRemote:output_type -> sesame.v1alpha1.Remote
	0,  // 36: sesame.v1alpha1.Sesame.GetRemote:output_type -> sesame.v1alpha1.Remote
	26, // 37: sesame.v1alpha1.Sesame.DeleteRemote:output_type -> google.protobuf.Empty
	0,  // 38: sesame.v1alpha1.Sesame.UpdateRemote:output_type -> sesame.v1alpha1.Remote
	8,  // 39: sesame.v1alpha1.Sesame.ListRemotes:output_type -> sesame.v1alpha1.ListRemotesResponse
	1,  // 40: sesame.v1alpha1.Sesame.CreateEndpoint:output_type -> sesame.v1alpha1.Endpoint
	1,  // 41: sesame.v1alpha1.Sesame.GetEndpoint:output_type -> sesame.v1alpha1.Endpoint
	26, // 42: sesame.v1alpha1.Sesame.DeleteEndpoint:output_type -> google.protobuf.Empty
	1,  // 43: sesame.v1alpha1.Sesame.UpdateEndpoint:output_type -> sesame.v1alpha1.Endpoint
	14, // 44: sesame.v1alpha1.Sesame.ListEndpoints:output_type -> sesame.v1alpha1.ListEndpointsResponse
	16, // 45: sesame.v1alpha1.Sesame.Proxy:output_type -> sesame.v1alpha1.ProxyResponse
	35, // [35:46] is the sub-list for method output_type
	24, // [24:35] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_sesame_v1alpha1_sesame_proto_init() }
func file_sesame_v1alpha1_sesame_proto_init() {
	if File_sesame_v1alpha1_sesame_proto != nil {
		return
	}
	file_sesame_v1alpha1_sesame_proto_msgTypes[15].OneofWrappers = []any{
		(*ProxyRequest_Dial_)(nil),
		(*ProxyRequest_Header)(nil),
		(*ProxyRequest_Content)(nil),
	}
	file_sesame_v1alpha1_sesame_proto_msgTypes[16].OneofWrappers = []any{
		(*ProxyResponse_Conn_)(nil),
		(*ProxyResponse_Error)(nil),
		(*ProxyResponse_Header)(nil),
		(*ProxyResponse_Content)(nil),
		(*ProxyResponse_Trailer)(nil),
	}
	file_sesame_v1alpha1_sesame_proto_msgTypes[17].OneofWrappers = []any{
		(*Endpoint_Spec_Tunnel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sesame_v1alpha1_sesame_proto_rawDesc), len(file_sesame_v1alpha1_sesame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sesame_v1alpha1_sesame_proto_goTypes,
		DependencyIndexes: file_sesame_v1alpha1_sesame_proto_depIdxs,
		MessageInfos:      file_sesame_v1alpha1_sesame_proto_msgTypes,
	}.Build()
	File_sesame_v1alpha1_sesame_proto = out.File
	file_sesame_v1alpha1_sesame_proto_goTypes = nil
	file_sesame_v1alpha1_sesame_proto_depIdxs = nil
}
