// Code generated by protoc-gen-go-copy. DO NOT EDIT.
// source: sesame/v1alpha1/sesame.proto

package api

import "github.com/joeycumines/sesame/type/grpcmetadata"
import "google.golang.org/genproto/googleapis/rpc/status"
import "google.golang.org/protobuf/types/known/anypb"
import "google.golang.org/protobuf/types/known/fieldmaskpb"
import "google.golang.org/protobuf/types/known/timestamppb"

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *Remote) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *Remote:
		x.Name = v.GetName()
		x.DisplayName = v.GetDisplayName()
		x.Description = v.GetDescription()
		x.CreateTime = v.GetCreateTime()
	default:
		if v, ok := v.(interface{ GetName() string }); ok {
			x.Name = v.GetName()
		}
		if v, ok := v.(interface{ GetDisplayName() string }); ok {
			x.DisplayName = v.GetDisplayName()
		}
		if v, ok := v.(interface{ GetDescription() string }); ok {
			x.Description = v.GetDescription()
		}
		if v, ok := v.(interface{ GetCreateTime() *timestamppb.Timestamp }); ok {
			x.CreateTime = v.GetCreateTime()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *Remote) Proto_ShallowClone() (c *Remote) {
	if x != nil {
		c = new(Remote)
		c.Name = x.Name
		c.DisplayName = x.DisplayName
		c.Description = x.Description
		c.CreateTime = x.CreateTime
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *Endpoint) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *Endpoint:
		x.Name = v.GetName()
		x.DisplayName = v.GetDisplayName()
		x.Description = v.GetDescription()
		x.CreateTime = v.GetCreateTime()
		x.Spec = v.GetSpec()
	default:
		if v, ok := v.(interface{ GetName() string }); ok {
			x.Name = v.GetName()
		}
		if v, ok := v.(interface{ GetDisplayName() string }); ok {
			x.DisplayName = v.GetDisplayName()
		}
		if v, ok := v.(interface{ GetDescription() string }); ok {
			x.Description = v.GetDescription()
		}
		if v, ok := v.(interface{ GetCreateTime() *timestamppb.Timestamp }); ok {
			x.CreateTime = v.GetCreateTime()
		}
		if v, ok := v.(interface{ GetSpec() *Endpoint_Spec }); ok {
			x.Spec = v.GetSpec()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *Endpoint) Proto_ShallowClone() (c *Endpoint) {
	if x != nil {
		c = new(Endpoint)
		c.Name = x.Name
		c.DisplayName = x.DisplayName
		c.Description = x.Description
		c.CreateTime = x.CreateTime
		c.Spec = x.Spec
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *Endpoint_Spec) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *Endpoint_Spec:
		x.Data = v.GetData()
	default:
		if v, ok := v.(interface{ GetData() isEndpoint_Spec_Data }); ok {
			x.Data = v.GetData()
		} else {
			func() {
				if v, ok := v.(interface{ GetTunnel() *Endpoint_Tunnel }); ok {
					var defaultValue *Endpoint_Tunnel
					if v := v.GetTunnel(); v != defaultValue {
						x.Data = &Endpoint_Spec_Tunnel{Tunnel: v}
						return
					}
				}
			}()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *Endpoint_Spec) Proto_ShallowClone() (c *Endpoint_Spec) {
	if x != nil {
		c = new(Endpoint_Spec)
		c.Data = x.Data
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *Endpoint_Tunnel) Proto_ShallowCopy(v interface{}) {
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *Endpoint_Tunnel) Proto_ShallowClone() (c *Endpoint_Tunnel) {
	if x != nil {
		c = new(Endpoint_Tunnel)
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *Namespace) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *Namespace:
		x.Name = v.GetName()
	default:
		if v, ok := v.(interface{ GetName() string }); ok {
			x.Name = v.GetName()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *Namespace) Proto_ShallowClone() (c *Namespace) {
	if x != nil {
		c = new(Namespace)
		c.Name = x.Name
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *CreateRemoteRequest) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *CreateRemoteRequest:
		x.Parent = v.GetParent()
		x.ResourceId = v.GetResourceId()
		x.Remote = v.GetRemote()
	default:
		if v, ok := v.(interface{ GetParent() string }); ok {
			x.Parent = v.GetParent()
		}
		if v, ok := v.(interface{ GetResourceId() string }); ok {
			x.ResourceId = v.GetResourceId()
		}
		if v, ok := v.(interface{ GetRemote() *Remote }); ok {
			x.Remote = v.GetRemote()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *CreateRemoteRequest) Proto_ShallowClone() (c *CreateRemoteRequest) {
	if x != nil {
		c = new(CreateRemoteRequest)
		c.Parent = x.Parent
		c.ResourceId = x.ResourceId
		c.Remote = x.Remote
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *GetRemoteRequest) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *GetRemoteRequest:
		x.Name = v.GetName()
	default:
		if v, ok := v.(interface{ GetName() string }); ok {
			x.Name = v.GetName()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *GetRemoteRequest) Proto_ShallowClone() (c *GetRemoteRequest) {
	if x != nil {
		c = new(GetRemoteRequest)
		c.Name = x.Name
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *DeleteRemoteRequest) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *DeleteRemoteRequest:
		x.Name = v.GetName()
	default:
		if v, ok := v.(interface{ GetName() string }); ok {
			x.Name = v.GetName()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *DeleteRemoteRequest) Proto_ShallowClone() (c *DeleteRemoteRequest) {
	if x != nil {
		c = new(DeleteRemoteRequest)
		c.Name = x.Name
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *UpdateRemoteRequest) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *UpdateRemoteRequest:
		x.Name = v.GetName()
		x.UpdateMask = v.GetUpdateMask()
		x.Remote = v.GetRemote()
	default:
		if v, ok := v.(interface{ GetName() string }); ok {
			x.Name = v.GetName()
		}
		if v, ok := v.(interface{ GetUpdateMask() *fieldmaskpb.FieldMask }); ok {
			x.UpdateMask = v.GetUpdateMask()
		}
		if v, ok := v.(interface{ GetRemote() *Remote }); ok {
			x.Remote = v.GetRemote()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *UpdateRemoteRequest) Proto_ShallowClone() (c *UpdateRemoteRequest) {
	if x != nil {
		c = new(UpdateRemoteRequest)
		c.Name = x.Name
		c.UpdateMask = x.UpdateMask
		c.Remote = x.Remote
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *ListRemotesRequest) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *ListRemotesRequest:
		x.Parent = v.GetParent()
		x.PageSize = v.GetPageSize()
		x.PageToken = v.GetPageToken()
	default:
		if v, ok := v.(interface{ GetParent() string }); ok {
			x.Parent = v.GetParent()
		}
		if v, ok := v.(interface{ GetPageSize() rune }); ok {
			x.PageSize = v.GetPageSize()
		}
		if v, ok := v.(interface{ GetPageToken() string }); ok {
			x.PageToken = v.GetPageToken()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *ListRemotesRequest) Proto_ShallowClone() (c *ListRemotesRequest) {
	if x != nil {
		c = new(ListRemotesRequest)
		c.Parent = x.Parent
		c.PageSize = x.PageSize
		c.PageToken = x.PageToken
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *ListRemotesResponse) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *ListRemotesResponse:
		x.Remotes = v.GetRemotes()
		x.NextPageToken = v.GetNextPageToken()
	default:
		if v, ok := v.(interface{ GetRemotes() []*Remote }); ok {
			x.Remotes = v.GetRemotes()
		}
		if v, ok := v.(interface{ GetNextPageToken() string }); ok {
			x.NextPageToken = v.GetNextPageToken()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *ListRemotesResponse) Proto_ShallowClone() (c *ListRemotesResponse) {
	if x != nil {
		c = new(ListRemotesResponse)
		c.Remotes = x.Remotes
		c.NextPageToken = x.NextPageToken
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *CreateEndpointRequest) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *CreateEndpointRequest:
		x.Parent = v.GetParent()
		x.ResourceId = v.GetResourceId()
		x.Endpoint = v.GetEndpoint()
	default:
		if v, ok := v.(interface{ GetParent() string }); ok {
			x.Parent = v.GetParent()
		}
		if v, ok := v.(interface{ GetResourceId() string }); ok {
			x.ResourceId = v.GetResourceId()
		}
		if v, ok := v.(interface{ GetEndpoint() *Endpoint }); ok {
			x.Endpoint = v.GetEndpoint()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *CreateEndpointRequest) Proto_ShallowClone() (c *CreateEndpointRequest) {
	if x != nil {
		c = new(CreateEndpointRequest)
		c.Parent = x.Parent
		c.ResourceId = x.ResourceId
		c.Endpoint = x.Endpoint
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *GetEndpointRequest) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *GetEndpointRequest:
		x.Name = v.GetName()
	default:
		if v, ok := v.(interface{ GetName() string }); ok {
			x.Name = v.GetName()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *GetEndpointRequest) Proto_ShallowClone() (c *GetEndpointRequest) {
	if x != nil {
		c = new(GetEndpointRequest)
		c.Name = x.Name
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *DeleteEndpointRequest) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *DeleteEndpointRequest:
		x.Name = v.GetName()
	default:
		if v, ok := v.(interface{ GetName() string }); ok {
			x.Name = v.GetName()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *DeleteEndpointRequest) Proto_ShallowClone() (c *DeleteEndpointRequest) {
	if x != nil {
		c = new(DeleteEndpointRequest)
		c.Name = x.Name
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *UpdateEndpointRequest) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *UpdateEndpointRequest:
		x.Name = v.GetName()
		x.UpdateMask = v.GetUpdateMask()
		x.Endpoint = v.GetEndpoint()
	default:
		if v, ok := v.(interface{ GetName() string }); ok {
			x.Name = v.GetName()
		}
		if v, ok := v.(interface{ GetUpdateMask() *fieldmaskpb.FieldMask }); ok {
			x.UpdateMask = v.GetUpdateMask()
		}
		if v, ok := v.(interface{ GetEndpoint() *Endpoint }); ok {
			x.Endpoint = v.GetEndpoint()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *UpdateEndpointRequest) Proto_ShallowClone() (c *UpdateEndpointRequest) {
	if x != nil {
		c = new(UpdateEndpointRequest)
		c.Name = x.Name
		c.UpdateMask = x.UpdateMask
		c.Endpoint = x.Endpoint
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *ListEndpointsRequest) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *ListEndpointsRequest:
		x.Parent = v.GetParent()
		x.PageSize = v.GetPageSize()
		x.PageToken = v.GetPageToken()
	default:
		if v, ok := v.(interface{ GetParent() string }); ok {
			x.Parent = v.GetParent()
		}
		if v, ok := v.(interface{ GetPageSize() rune }); ok {
			x.PageSize = v.GetPageSize()
		}
		if v, ok := v.(interface{ GetPageToken() string }); ok {
			x.PageToken = v.GetPageToken()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *ListEndpointsRequest) Proto_ShallowClone() (c *ListEndpointsRequest) {
	if x != nil {
		c = new(ListEndpointsRequest)
		c.Parent = x.Parent
		c.PageSize = x.PageSize
		c.PageToken = x.PageToken
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *ListEndpointsResponse) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *ListEndpointsResponse:
		x.Endpoints = v.GetEndpoints()
		x.NextPageToken = v.GetNextPageToken()
	default:
		if v, ok := v.(interface{ GetEndpoints() []*Endpoint }); ok {
			x.Endpoints = v.GetEndpoints()
		}
		if v, ok := v.(interface{ GetNextPageToken() string }); ok {
			x.NextPageToken = v.GetNextPageToken()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *ListEndpointsResponse) Proto_ShallowClone() (c *ListEndpointsResponse) {
	if x != nil {
		c = new(ListEndpointsResponse)
		c.Endpoints = x.Endpoints
		c.NextPageToken = x.NextPageToken
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *ProxyRequest) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *ProxyRequest:
		x.Data = v.GetData()
	default:
		if v, ok := v.(interface{ GetData() isProxyRequest_Data }); ok {
			x.Data = v.GetData()
		} else {
			func() {
				if v, ok := v.(interface{ GetDial() *ProxyRequest_Dial }); ok {
					var defaultValue *ProxyRequest_Dial
					if v := v.GetDial(); v != defaultValue {
						x.Data = &ProxyRequest_Dial_{Dial: v}
						return
					}
				}
				if v, ok := v.(interface {
					GetHeader() *grpcmetadata.GrpcMetadata
				}); ok {
					var defaultValue *grpcmetadata.GrpcMetadata
					if v := v.GetHeader(); v != defaultValue {
						x.Data = &ProxyRequest_Header{Header: v}
						return
					}
				}
				if v, ok := v.(interface{ GetContent() *anypb.Any }); ok {
					var defaultValue *anypb.Any
					if v := v.GetContent(); v != defaultValue {
						x.Data = &ProxyRequest_Content{Content: v}
						return
					}
				}
			}()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *ProxyRequest) Proto_ShallowClone() (c *ProxyRequest) {
	if x != nil {
		c = new(ProxyRequest)
		c.Data = x.Data
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *ProxyRequest_Dial) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *ProxyRequest_Dial:
		x.Endpoint = v.GetEndpoint()
		x.Method = v.GetMethod()
		x.ConnMask = v.GetConnMask()
	default:
		if v, ok := v.(interface{ GetEndpoint() string }); ok {
			x.Endpoint = v.GetEndpoint()
		}
		if v, ok := v.(interface{ GetMethod() string }); ok {
			x.Method = v.GetMethod()
		}
		if v, ok := v.(interface{ GetConnMask() *fieldmaskpb.FieldMask }); ok {
			x.ConnMask = v.GetConnMask()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *ProxyRequest_Dial) Proto_ShallowClone() (c *ProxyRequest_Dial) {
	if x != nil {
		c = new(ProxyRequest_Dial)
		c.Endpoint = x.Endpoint
		c.Method = x.Method
		c.ConnMask = x.ConnMask
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *ProxyResponse) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *ProxyResponse:
		x.Data = v.GetData()
	default:
		if v, ok := v.(interface{ GetData() isProxyResponse_Data }); ok {
			x.Data = v.GetData()
		} else {
			func() {
				if v, ok := v.(interface{ GetConn() *ProxyResponse_Conn }); ok {
					var defaultValue *ProxyResponse_Conn
					if v := v.GetConn(); v != defaultValue {
						x.Data = &ProxyResponse_Conn_{Conn: v}
						return
					}
				}
				if v, ok := v.(interface{ GetError() *status.Status }); ok {
					var defaultValue *status.Status
					if v := v.GetError(); v != defaultValue {
						x.Data = &ProxyResponse_Error{Error: v}
						return
					}
				}
				if v, ok := v.(interface {
					GetHeader() *grpcmetadata.GrpcMetadata
				}); ok {
					var defaultValue *grpcmetadata.GrpcMetadata
					if v := v.GetHeader(); v != defaultValue {
						x.Data = &ProxyResponse_Header{Header: v}
						return
					}
				}
				if v, ok := v.(interface{ GetContent() *anypb.Any }); ok {
					var defaultValue *anypb.Any
					if v := v.GetContent(); v != defaultValue {
						x.Data = &ProxyResponse_Content{Content: v}
						return
					}
				}
				if v, ok := v.(interface {
					GetTrailer() *grpcmetadata.GrpcMetadata
				}); ok {
					var defaultValue *grpcmetadata.GrpcMetadata
					if v := v.GetTrailer(); v != defaultValue {
						x.Data = &ProxyResponse_Trailer{Trailer: v}
						return
					}
				}
			}()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *ProxyResponse) Proto_ShallowClone() (c *ProxyResponse) {
	if x != nil {
		c = new(ProxyResponse)
		c.Data = x.Data
	}
	return
}

// Proto_ShallowCopy copies fields, from v to the receiver, using field getters.
// Note that v is of an arbitrary type, which may implement any number of the
// field getters, which are defined as any methods of the same signature as those
// generated for the receiver type, with a name starting with Get.
// WARNING: Optional fields may be ignored, if v is not the receiver type.
func (x *ProxyResponse_Conn) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *ProxyResponse_Conn:
		x.Namespace = v.GetNamespace()
		x.Remote = v.GetRemote()
		x.Endpoint = v.GetEndpoint()
	default:
		if v, ok := v.(interface{ GetNamespace() *Namespace }); ok {
			x.Namespace = v.GetNamespace()
		}
		if v, ok := v.(interface{ GetRemote() *Remote }); ok {
			x.Remote = v.GetRemote()
		}
		if v, ok := v.(interface{ GetEndpoint() *Endpoint }); ok {
			x.Endpoint = v.GetEndpoint()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *ProxyResponse_Conn) Proto_ShallowClone() (c *ProxyResponse_Conn) {
	if x != nil {
		c = new(ProxyResponse_Conn)
		c.Namespace = x.Namespace
		c.Remote = x.Remote
		c.Endpoint = x.Endpoint
	}
	return
}
