openapi: 3.0.1
info:
  title: sesame/v1alpha1/sesame.proto
  contact:
    name: Sesame project
    url: https://github.com/joeycumines/sesame
  license:
    name: MIT License
    url: https://github.com/joeycumines/sesame/blob/main/LICENSE
  version: 0.1.0-alpha1
externalDocs:
  description: Source repository
  url: https://github.com/joeycumines/sesame
servers:
- url: /
tags:
- name: Sesame
  description: "Sesame is the core management and registration API, used to configure\
    \ and orchestrate access to remotes."
paths:
  /v1alpha1/proxy:
    post:
      tags:
      - Sesame
      operationId: Sesame_Proxy
      requestBody:
        description: ' (streaming inputs)'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1alpha1ProxyRequest'
        required: true
      responses:
        "200":
          description: A successful response.(streaming responses)
          content:
            application/json:
              schema:
                title: Stream result of v1alpha1ProxyResponse
                type: object
                properties:
                  result:
                    $ref: '#/components/schemas/v1alpha1ProxyResponse'
                  error:
                    $ref: '#/components/schemas/rpcStatus'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      x-codegen-request-body-name: body
  /v1alpha1/{name_1}:
    get:
      tags:
      - Sesame
      operationId: Sesame_GetEndpoint
      parameters:
      - name: name_1
        in: path
        required: true
        schema:
          pattern: "namespaces/[^/]+/remotes/[^/]+/endpoints/[^/]+"
          type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1alpha1Endpoint'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
    delete:
      tags:
      - Sesame
      operationId: Sesame_DeleteEndpoint
      parameters:
      - name: name_1
        in: path
        required: true
        schema:
          pattern: "namespaces/[^/]+/remotes/[^/]+/endpoints/[^/]+"
          type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
    patch:
      tags:
      - Sesame
      operationId: Sesame_UpdateEndpoint
      parameters:
      - name: name_1
        in: path
        required: true
        schema:
          pattern: "namespaces/[^/]+/remotes/[^/]+/endpoints/[^/]+"
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1alpha1Endpoint'
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1alpha1Endpoint'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      x-codegen-request-body-name: endpoint
  /v1alpha1/{name}:
    get:
      tags:
      - Sesame
      operationId: Sesame_GetRemote
      parameters:
      - name: name
        in: path
        required: true
        schema:
          pattern: "namespaces/[^/]+/remotes/[^/]+"
          type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1alpha1Remote'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
    delete:
      tags:
      - Sesame
      operationId: Sesame_DeleteRemote
      parameters:
      - name: name
        in: path
        required: true
        schema:
          pattern: "namespaces/[^/]+/remotes/[^/]+"
          type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
    patch:
      tags:
      - Sesame
      operationId: Sesame_UpdateRemote
      parameters:
      - name: name
        in: path
        required: true
        schema:
          pattern: "namespaces/[^/]+/remotes/[^/]+"
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1alpha1Remote'
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1alpha1Remote'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      x-codegen-request-body-name: remote
  /v1alpha1/{parent}/endpoints:
    get:
      tags:
      - Sesame
      operationId: Sesame_ListEndpoints
      parameters:
      - name: parent
        in: path
        required: true
        schema:
          pattern: "namespaces/[^/]+/remotes/[^/]+"
          type: string
      - name: pageSize
        in: query
        schema:
          type: integer
          format: int32
      - name: pageToken
        in: query
        schema:
          type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1alpha1ListEndpointsResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
    post:
      tags:
      - Sesame
      operationId: Sesame_CreateEndpoint
      parameters:
      - name: parent
        in: path
        description: "The name of the parent Remote, note that endpoint.name MUST\
          \ NOT be set."
        required: true
        schema:
          pattern: "namespaces/[^/]+/remotes/[^/]+"
          type: string
      - name: resourceId
        in: query
        description: "May be specified to request a specific (non-trailing) resource\
          \ id, note it's a single path segment, w/o any \"/\"."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1alpha1Endpoint'
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1alpha1Endpoint'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      x-codegen-request-body-name: endpoint
  /v1alpha1/{parent}/remotes:
    get:
      tags:
      - Sesame
      operationId: Sesame_ListRemotes
      parameters:
      - name: parent
        in: path
        required: true
        schema:
          pattern: "namespaces/[^/]+"
          type: string
      - name: pageSize
        in: query
        schema:
          type: integer
          format: int32
      - name: pageToken
        in: query
        schema:
          type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1alpha1ListRemotesResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
    post:
      tags:
      - Sesame
      operationId: Sesame_CreateRemote
      parameters:
      - name: parent
        in: path
        description: "The name of the parent Namespace, note that remote.name MUST\
          \ NOT be set."
        required: true
        schema:
          pattern: "namespaces/[^/]+"
          type: string
      - name: resourceId
        in: query
        description: "May be specified to request a specific (non-trailing) resource\
          \ id, note it's a single path segment, w/o any \"/\"."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1alpha1Remote'
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1alpha1Remote'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      x-codegen-request-body-name: remote
components:
  schemas:
    EndpointSpec:
      type: object
      properties:
        tunnel:
          $ref: '#/components/schemas/EndpointTunnel'
      description: "Spec models the endpoint specification, containing configuration\
        \ around access and usage behavior."
    EndpointTunnel:
      type: object
      description: |-
        Tunnel models an endpoint exposed directly over a tunnel provider.

        TODO might eventually make this configurable (more than one tunnel pattern)
    GrpcMetadataBin:
      type: object
      properties:
        values:
          type: array
          items:
            pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
            type: string
            format: byte
    GrpcMetadataStr:
      type: object
      properties:
        values:
          type: array
          items:
            type: string
    ProxyRequestDial:
      type: object
      properties:
        endpoint:
          type: string
        method:
          type: string
        connMask:
          type: string
          description: conn_mask is an optional field mask for ProxyResponse.conn.
      description: Dial models the initial request routing of a method call.
    ProxyResponseConn:
      type: object
      properties:
        namespace:
          $ref: '#/components/schemas/v1alpha1Namespace'
        remote:
          $ref: '#/components/schemas/v1alpha1Remote'
        endpoint:
          $ref: '#/components/schemas/v1alpha1Endpoint'
      description: Conn is the response to ProxyRequest.dial.
    protobufAny:
      type: object
      properties:
        '@type':
          type: string
          description: |-
            Identifies the type of the serialized Protobuf message with a URI reference
            consisting of a prefix ending in a slash and the fully-qualified type name.

            Example: type.googleapis.com/google.protobuf.StringValue

            This string must contain at least one `/` character, and the content after
            the last `/` must be the fully-qualified name of the type in canonical
            form, without a leading dot. Do not write a scheme on these URI references
            so that clients do not attempt to contact them.

            The prefix is arbitrary and Protobuf implementations are expected to
            simply strip off everything up to and including the last `/` to identify
            the type. `type.googleapis.com/` is a common default prefix that some
            legacy implementations require. This prefix does not indicate the origin of
            the type, and URIs containing it are not expected to respond to any
            requests.

            All type URL strings must be legal URI references with the additional
            restriction (for the text format) that the content of the reference
            must consist only of alphanumeric characters, percent-encoded escapes, and
            characters in the following set (not including the outer backticks):
            `/-.~_!$&()*+,;=`. Despite our allowing percent encodings, implementations
            should not unescape them to prevent confusion with existing parsers. For
            example, `type.googleapis.com%2FFoo` should be rejected.

            In the original design of `Any`, the possibility of launching a type
            resolution service at these type URLs was considered but Protobuf never
            implemented one and considers contacting these URLs to be problematic and
            a potential security issue. Do not attempt to contact type URLs.
      additionalProperties:
        type: object
      description: |-
        `Any` contains an arbitrary serialized protocol buffer message along with a
        URL that describes the type of the serialized message.

        In its binary encoding, an `Any` is an ordinary message; but in other wire
        forms like JSON, it has a special encoding. The format of the type URL is
        described on the `type_url` field.

        Protobuf APIs provide utilities to interact with `Any` values:

        - A 'pack' operation accepts a message and constructs a generic `Any` wrapper
          around it.
        - An 'unpack' operation reads the content of an `Any` message, either into an
          existing message or a new one. Unpack operations must check the type of the
          value they unpack against the declared `type_url`.
        - An 'is' operation decides whether an `Any` contains a message of the given
          type, i.e. whether it can 'unpack' that type.

        The JSON format representation of an `Any` follows one of these cases:

        - For types without special-cased JSON encodings, the JSON format
          representation of the `Any` is the same as that of the message, with an
          additional `@type` field which contains the type URL.
        - For types with special-cased JSON encodings (typically called 'well-known'
          types, listed in https://protobuf.dev/programming-guides/json/#any), the
          JSON format representation has a key `@type` which contains the type URL
          and a key `value` which contains the JSON-serialized value.

        The text format representation of an `Any` is like a message with one field
        whose name is the type URL in brackets. For example, an `Any` containing a
        `foo.Bar` message may be written `[type.googleapis.com/foo.Bar] { a: 2 }`.
    rpcStatus:
      type: object
      properties:
        code:
          type: integer
          description: |-
            The status code, which should be an enum value of
            [google.rpc.Code][google.rpc.Code].
          format: int32
        message:
          type: string
          description: |-
            A developer-facing error message, which should be in English. Any
            user-facing error message should be localized and sent in the
            [google.rpc.Status.details][google.rpc.Status.details] field, or localized
            by the client.
        details:
          type: array
          description: |-
            A list of messages that carry the error details.  There is a common set of
            message types for APIs to use.
          items:
            $ref: '#/components/schemas/protobufAny'
      description: |-
        The `Status` type defines a logical error model that is suitable for
        different programming environments, including REST APIs and RPC APIs. It is
        used by [gRPC](https://github.com/grpc). Each `Status` message contains
        three pieces of data: error code, error message, and error details.

        You can find out more about this error model and how to work with it in the
        [API Design Guide](https://cloud.google.com/apis/design/errors).
    typeGrpcMetadata:
      type: object
      properties:
        data:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/typeGrpcMetadataValue'
      description: "GrpcMetadata represents gRPC request or response (header, trailer)\
        \ metadata."
    typeGrpcMetadataValue:
      type: object
      properties:
        str:
          $ref: '#/components/schemas/GrpcMetadataStr'
        bin:
          $ref: '#/components/schemas/GrpcMetadataBin'
    v1alpha1Endpoint:
      type: object
      properties:
        name:
          type: string
          readOnly: true
        displayName:
          type: string
        description:
          type: string
        createTime:
          type: string
          format: date-time
          readOnly: true
        spec:
          $ref: '#/components/schemas/EndpointSpec'
      description: Endpoint is a gRPC service available via a remote.
    v1alpha1ListEndpointsResponse:
      type: object
      properties:
        endpoints:
          type: array
          items:
            $ref: '#/components/schemas/v1alpha1Endpoint'
        nextPageToken:
          type: string
    v1alpha1ListRemotesResponse:
      type: object
      properties:
        remotes:
          type: array
          items:
            $ref: '#/components/schemas/v1alpha1Remote'
        nextPageToken:
          type: string
    v1alpha1Namespace:
      type: object
      properties:
        name:
          type: string
          readOnly: true
      description: "Namespace scopes resources in the Sesame API, and is intended\
        \ to (eventually) facilitate scoped simple auth."
    v1alpha1ProxyRequest:
      type: object
      properties:
        dial:
          $ref: '#/components/schemas/ProxyRequestDial'
        header:
          $ref: '#/components/schemas/typeGrpcMetadata'
        content:
          $ref: '#/components/schemas/protobufAny'
    v1alpha1ProxyResponse:
      type: object
      properties:
        conn:
          $ref: '#/components/schemas/ProxyResponseConn'
        error:
          $ref: '#/components/schemas/rpcStatus'
        header:
          $ref: '#/components/schemas/typeGrpcMetadata'
        content:
          $ref: '#/components/schemas/protobufAny'
        trailer:
          $ref: '#/components/schemas/typeGrpcMetadata'
    v1alpha1Remote:
      type: object
      properties:
        name:
          type: string
          readOnly: true
        displayName:
          type: string
        description:
          type: string
        createTime:
          type: string
          format: date-time
          readOnly: true
      description: Remote is a network device or other resource that may be accessed
        by Sesame clients.
x-original-swagger-version: "2.0"
