// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: sesame/type/netaddr.proto

package netaddr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NetAddr represents a network end point address.
//
// The two fields network and address are conventionally strings that can be passed as the arguments to Go's net.Dial,
// but the exact form and meaning of the strings is up to the implementation.
//
// See also Go's net.Addr interface.
type NetAddr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetAddr) Reset() {
	*x = NetAddr{}
	mi := &file_sesame_type_netaddr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetAddr) ProtoMessage() {}

func (x *NetAddr) ProtoReflect() protoreflect.Message {
	mi := &file_sesame_type_netaddr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetAddr.ProtoReflect.Descriptor instead.
func (*NetAddr) Descriptor() ([]byte, []int) {
	return file_sesame_type_netaddr_proto_rawDescGZIP(), []int{0}
}

func (x *NetAddr) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *NetAddr) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_sesame_type_netaddr_proto protoreflect.FileDescriptor

const file_sesame_type_netaddr_proto_rawDesc = "" +
	"\n" +
	"\x19sesame/type/netaddr.proto\x12\vsesame.type\"=\n" +
	"\aNetAddr\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddressB,Z*github.com/joeycumines/sesame/type/netaddrb\x06proto3"

var (
	file_sesame_type_netaddr_proto_rawDescOnce sync.Once
	file_sesame_type_netaddr_proto_rawDescData []byte
)

func file_sesame_type_netaddr_proto_rawDescGZIP() []byte {
	file_sesame_type_netaddr_proto_rawDescOnce.Do(func() {
		file_sesame_type_netaddr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sesame_type_netaddr_proto_rawDesc), len(file_sesame_type_netaddr_proto_rawDesc)))
	})
	return file_sesame_type_netaddr_proto_rawDescData
}

var file_sesame_type_netaddr_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sesame_type_netaddr_proto_goTypes = []any{
	(*NetAddr)(nil), // 0: sesame.type.NetAddr
}
var file_sesame_type_netaddr_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sesame_type_netaddr_proto_init() }
func file_sesame_type_netaddr_proto_init() {
	if File_sesame_type_netaddr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sesame_type_netaddr_proto_rawDesc), len(file_sesame_type_netaddr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sesame_type_netaddr_proto_goTypes,
		DependencyIndexes: file_sesame_type_netaddr_proto_depIdxs,
		MessageInfos:      file_sesame_type_netaddr_proto_msgTypes,
	}.Build()
	File_sesame_type_netaddr_proto = out.File
	file_sesame_type_netaddr_proto_goTypes = nil
	file_sesame_type_netaddr_proto_depIdxs = nil
}
